
export type CardData = {
  id: string;
  name: string;
  cost: number;
  attack: number;
  health: number;
  description: string;
  image: string;
  class: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
  mechanics?: string[];
};

export const allCards: CardData[] = [
  {
    id: '001',
    name: 'Waldhauch',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Zieht eine Karte.',
    image: '/cards/001.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '002',
    name: 'Rindenhaut-Schützer',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Schild (Spott).',
    image: '/cards/002.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '003',
    name: 'Lebenswurzel',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Stellt 4 Leben wieder her.',
    image: '/cards/003.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['heal']
  },
  {
    id: '004',
    name: 'Zornklinge',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Ansturm.',
    image: '/cards/004.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '005',
    name: 'Magmaschlag',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 6 Schaden.',
    image: '/cards/005.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['damage']
  },
  {
    id: '006',
    name: 'Lichtnova',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen Feinden.',
    image: '/cards/006.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['aoe']
  },
  {
    id: '007',
    name: 'Schattengeist',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Beim Ausspielen: Gegner verliert 2 Leben.',
    image: '/cards/007.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['battlecry']
  },
  {
    id: '008',
    name: 'Windwandler',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Doppelschlag (Greift zweimal an).',
    image: '/cards/008.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '009',
    name: 'Klingenhexe',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Kampfschrei: Fügt einem Gegner 3 Schaden zu.',
    image: '/cards/009.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['battlecry']
  },
  {
    id: '010',
    name: 'Auge des Waldes',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Ziehe 2 Karten.',
    image: '/cards/010.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '011',
    name: 'Dämonenstoß',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden.',
    image: '/cards/011.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '012',
    name: 'Kristallheiler',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Heilt 3 Leben bei allen Verbündeten.',
    image: '/cards/012.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['aoe', 'heal']
  },
  {
    id: '013',
    name: 'Nebelkrieger',
    cost: 2,
    attack: 3,
    health: 1,
    description: 'Verborgensein.',
    image: '/cards/013.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '014',
    name: 'Runenwächter',
    cost: 5,
    attack: 4,
    health: 6,
    description: 'Schild.',
    image: '/cards/014.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '015',
    name: 'Flammenbote',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Zauberschaden +1.',
    image: '/cards/015.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '016',
    name: 'Todeshauch',
    cost: 4,
    attack: 2,
    health: 4,
    description: 'Todesröcheln: Verursacht 2 Schaden an allen Gegnern.',
    image: '/cards/016.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['deathrattle']
  },
  {
    id: '017',
    name: 'Seelenbrenner',
    cost: 5,
    attack: 5,
    health: 4,
    description: 'Beim Ausspielen: Ziehe eine Karte.',
    image: '/cards/017.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['battlecry', 'draw']
  },
  {
    id: '018',
    name: 'Donnerfaust',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Ansturm.',
    image: '/cards/018.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '019',
    name: 'Wachposten',
    cost: 2,
    attack: 1,
    health: 4,
    description: 'Schild.',
    image: '/cards/019.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '020',
    name: 'Lichtfunken',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Heilt 2 Leben.',
    image: '/cards/020.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['heal']
  }
    {
    id: '021',
    name: 'Seelensucher',
    cost: 3,
    attack: 2,
    health: 4,
    description: 'Todesröcheln: Ziehe eine Karte.',
    image: '/cards/021.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['deathrattle', 'draw']
  },
  {
    id: '022',
    name: 'Naturpfad',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Erhalte 2 Mana in diesem Zug.',
    image: '/cards/022.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['manaboost']
  },
  {
    id: '023',
    name: 'Stahlfalke',
    cost: 4,
    attack: 4,
    health: 3,
    description: 'Windzorn.',
    image: '/cards/023.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '024',
    name: 'Schattenflamme',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Opfere einen Diener. Verursacht dessen Angriff als Schaden an allen Gegnern.',
    image: '/cards/024.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['sacrifice', 'aoe']
  },
  {
    id: '025',
    name: 'Runenschlag',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden. Zauberschaden wird angerechnet.',
    image: '/cards/025.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['damage', 'spellpower']
  },
  {
    id: '026',
    name: 'Windgeheul',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Verleiht einem Diener +1 Angriff.',
    image: '/cards/026.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['battlecry', 'buff']
  },
  {
    id: '027',
    name: 'Splitterklinge',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Verborgensein.',
    image: '/cards/027.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '028',
    name: 'Glanzschild-Wächter',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Schild.',
    image: '/cards/028.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '029',
    name: 'Dunkelpriester',
    cost: 5,
    attack: 4,
    health: 4,
    description: 'Kampfschrei: Übernimmt die Kontrolle über einen feindlichen Diener mit 2 oder weniger Angriff.',
    image: '/cards/029.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'control']
  },
  {
    id: '030',
    name: 'Flammenschlag',
    cost: 7,
    attack: 0,
    health: 0,
    description: 'Verursacht 4 Schaden an allen gegnerischen Dienern.',
    image: '/cards/030.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '031',
    name: 'Pfadfinder',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Zieht eine Karte.',
    image: '/cards/031.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '032',
    name: 'Energiedieb',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Beim Ausspielen: Stehle 1 Mana-Kristall in diesem Zug.',
    image: '/cards/032.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'manasteal']
  },
  {
    id: '033',
    name: 'Wurzelkoloss',
    cost: 6,
    attack: 5,
    health: 6,
    description: 'Schild.',
    image: '/cards/033.jpg',
    class: 'Naturrufer',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '034',
    name: 'Dämonisches Feuer',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Fügt einem Diener 2 Schaden zu. Wenn es ein eigener Dämon ist, erhält er stattdessen +2/+2.',
    image: '/cards/034.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['damage', 'conditionalbuff']
  },
  {
    id: '035',
    name: 'Schildsänger',
    cost: 3,
    attack: 2,
    health: 5,
    description: 'Schild.',
    image: '/cards/035.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '036',
    name: 'Donnerzorn',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen Feinden.',
    image: '/cards/036.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '037',
    name: 'Dämmerungsmagier',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Zauberschaden +1.',
    image: '/cards/037.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '038',
    name: 'Waldläuferin',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Kampfschrei: Zieht 1 Karte.',
    image: '/cards/038.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['battlecry', 'draw']
  },
  {
    id: '039',
    name: 'Kettenblitz',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden an einem Ziel und 1 Schaden an benachbarten Zielen.',
    image: '/cards/039.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '040',
    name: 'Schattenläufer',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/040.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  }
  {
    id: '041',
    name: 'Kristallformer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Erhalte einen zusätzlichen Mana-Kristall in diesem Zug.',
    image: '/cards/041.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['battlecry', 'manaboost']
  },
  {
    id: '042',
    name: 'Echoschlitzer',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Windzorn.',
    image: '/cards/042.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '043',
    name: 'Lebensweber',
    cost: 4,
    attack: 2,
    health: 6,
    description: 'Am Ende deines Zuges: Heile deinen Helden um 2 Leben.',
    image: '/cards/043.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['healing', 'endofturn']
  },
  {
    id: '044',
    name: 'Sturmkralle',
    cost: 3,
    attack: 3,
    health: 2,
    description: 'Kampfschrei: Fügt einem feindlichen Diener 2 Schaden zu.',
    image: '/cards/044.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['battlecry', 'damage']
  },
  {
    id: '045',
    name: 'Dornenwächter',
    cost: 5,
    attack: 4,
    health: 6,
    description: 'Schild.',
    image: '/cards/045.jpg',
    class: 'Naturrufer',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '046',
    name: 'Dämonenzorn',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen nicht-dämonischen Dienern.',
    image: '/cards/046.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['aoe', 'conditional']
  },
  {
    id: '047',
    name: 'Frostklinge',
    cost: 2,
    attack: 3,
    health: 1,
    description: 'Einfrieren jedes Dieners, dem dieser Diener Schaden zufügt.',
    image: '/cards/047.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['freeze', 'damage']
  },
  {
    id: '048',
    name: 'Runenpriester',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Zauberschaden +1.',
    image: '/cards/048.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '049',
    name: 'Wurzelranke',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Kampfschrei: Heilt 2 Leben.',
    image: '/cards/049.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['battlecry', 'healing']
  },
  {
    id: '050',
    name: 'Blutpakt',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Ziehe 2 Karten und erhalte 3 Schaden.',
    image: '/cards/050.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['draw', 'selfdamage']
  },
  {
    id: '051',
    name: 'Lichtformer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Verleiht einem anderen Diener +1/+1.',
    image: '/cards/051.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['battlecry', 'buff']
  },
  {
    id: '052',
    name: 'Tiefenschleicher',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/052.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '053',
    name: 'Dunkelklaue',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Zufälliger Feind erhält 3 Schaden beim Ausspielen.',
    image: '/cards/053.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'randomdamage']
  },
  {
    id: '054',
    name: 'Kettenheiler',
    cost: 4,
    attack: 2,
    health: 6,
    description: 'Kampfschrei: Heilt 3 Leben bei allen verbündeten Charakteren.',
    image: '/cards/054.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['battlecry', 'aoehealing']
  },
  {
    id: '055',
    name: 'Energiefokus',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Ziehe eine Karte. Zauberschaden +1 für diesen Zug.',
    image: '/cards/055.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['draw', 'temporaryspellpower']
  },
  {
    id: '056',
    name: 'Wellenformer',
    cost: 4,
    attack: 2,
    health: 5,
    description: 'Windzorn.',
    image: '/cards/056.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['windfury']
  },
  {
    id: '057',
    name: 'Funkenschlag',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden. Wenn es einen Diener tötet, ziehe eine Karte.',
    image: '/cards/057.jpg',
    class: 'Waldhüter',
    rarity: 'rare',
    mechanics: ['damage', 'draw']
  },
  {
    id: '058',
    name: 'Geisterrausch',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Fügt allen Dienern 1 Schaden zu. Für jeden getöteten: Ziehe eine Karte.',
    image: '/cards/058.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'draw']
  },
  {
    id: '059',
    name: 'Höllenfeuer',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden an allen Charakteren.',
    image: '/cards/059.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '060',
    name: 'Astralkugel',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Ziehe 3 Karten.',
    image: '/cards/060.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['draw']
  }
  {
    id: '061',
    name: 'Schattenseherin',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Zauber kosten (1) weniger.',
    image: '/cards/061.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['spellcostreduction']
  },
  {
    id: '062',
    name: 'Kristallhieb',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden.',
    image: '/cards/062.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '063',
    name: 'Urwächter',
    cost: 6,
    attack: 6,
    health: 5,
    description: 'Schild.',
    image: '/cards/063.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '064',
    name: 'Lichturteil',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Zerstört einen feindlichen Diener mit 3 oder weniger Angriff.',
    image: '/cards/064.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['destroy', 'conditional']
  },
  {
    id: '065',
    name: 'Splitterklinge',
    cost: 3,
    attack: 4,
    health: 1,
    description: 'Durchbohren. Verursacht doppelten Schaden an Schilden.',
    image: '/cards/065.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['pierce', 'antitaunt']
  },
  {
    id: '066',
    name: 'Blutgesang',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Heilt 4 Leben.',
    image: '/cards/066.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['healing']
  },
  {
    id: '067',
    name: 'Donnerhau',
    cost: 4,
    attack: 5,
    health: 4,
    description: 'Kampfschrei: Füge einem Gegner 2 Schaden zu.',
    image: '/cards/067.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['battlecry', 'damage']
  },
  {
    id: '068',
    name: 'Waldschleicher',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/068.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '069',
    name: 'Manaspule',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Erhalte 1 Mana nur für diesen Zug.',
    image: '/cards/069.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['manaboost', 'temporary']
  },
  {
    id: '070',
    name: 'Knochengardist',
    cost: 4,
    attack: 3,
    health: 6,
    description: 'Schild.',
    image: '/cards/070.jpg',
    class: 'Klingenmeister',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '071',
    name: 'Wurzelnetz',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Einen Gegner festhalten (kann nächsten Zug nicht angreifen).',
    image: '/cards/071.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['disable', 'root']
  },
  {
    id: '072',
    name: 'Ritual des Schmerzes',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Füge ALLEN Dienern 2 Schaden zu.',
    image: '/cards/072.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '073',
    name: 'Funkenpriesterin',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Zauberschaden +1.',
    image: '/cards/073.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '074',
    name: 'Klingentänzerin',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Eile.',
    image: '/cards/074.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['rush']
  },
  {
    id: '075',
    name: 'Dunkelmeditation',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ziehe 2 Karten.',
    image: '/cards/075.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['draw']
  },
  {
    id: '076',
    name: 'Splitterregen',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Fügt allen feindlichen Dienern 2 Schaden zu.',
    image: '/cards/076.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '077',
    name: 'Heilende Aura',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Heilt 3 Leben bei allen verbündeten Charakteren.',
    image: '/cards/077.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['aoehealing']
  },
  {
    id: '078',
    name: 'Widerstandsschrei',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verleiht deinen Dienern +0/+2.',
    image: '/cards/078.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['buff']
  },
  {
    id: '079',
    name: 'Wacholderbär',
    cost: 5,
    attack: 5,
    health: 6,
    description: 'Schild.',
    image: '/cards/079.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '080',
    name: 'Blitzritual',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an einem Ziel. Überladung: 1',
    image: '/cards/080.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['damage', 'overload']
  }
  {
    id: '081',
    name: 'Zornkrähe',
    cost: 2,
    attack: 2,
    health: 1,
    description: 'Windzorn.',
    image: '/cards/081.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['windfury']
  },
  {
    id: '082',
    name: 'Lichtblitz',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 1 Schaden. Zauberschaden wirkt zusätzlich.',
    image: '/cards/082.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['damage', 'spellpower']
  },
  {
    id: '083',
    name: 'Schattenformer',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Kampfschrei: Verdoppelt den nächsten Zauber.',
    image: '/cards/083.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'spellboost']
  },
  {
    id: '084',
    name: 'Runenstecher',
    cost: 3,
    attack: 2,
    health: 4,
    description: 'Zauberschaden +1.',
    image: '/cards/084.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '085',
    name: 'Wurzelspeer',
    cost: 4,
    attack: 4,
    health: 4,
    description: 'Kampfschrei: Gibt Schild.',
    image: '/cards/085.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'taunt']
  },
  {
    id: '086',
    name: 'Klingenfurie',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Eile.',
    image: '/cards/086.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '087',
    name: 'Geisterklaue',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Unsichtbar.',
    image: '/cards/087.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '088',
    name: 'Aegis-Wächter',
    cost: 5,
    attack: 2,
    health: 7,
    description: 'Schild. Kann nicht betäubt werden.',
    image: '/cards/088.jpg',
    class: 'Klingenmeister',
    rarity: 'epic',
    mechanics: ['taunt', 'immunestun']
  },
  {
    id: '089',
    name: 'Schleiermagie',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Deine Diener erhalten Verborgensein für 1 Zug.',
    image: '/cards/089.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['stealth', 'temporary']
  },
  {
    id: '090',
    name: 'Lebensfunke',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Heilt 2 Leben und zieht eine Karte.',
    image: '/cards/090.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['healing', 'draw']
  },
  {
    id: '091',
    name: 'Kriegsbär',
    cost: 6,
    attack: 5,
    health: 6,
    description: 'Schild. Ansturm.',
    image: '/cards/091.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['taunt', 'rush']
  },
  {
    id: '092',
    name: 'Magmaschleuder',
    cost: 4,
    attack: 4,
    health: 3,
    description: 'Zauberschaden +2.',
    image: '/cards/092.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['spellpower']
  },
  {
    id: '093',
    name: 'Knochenrüstung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Dein Held erhält +5 Rüstung.',
    image: '/cards/093.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['armor']
  },
  {
    id: '094',
    name: 'Schattenschritt',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Bringe einen befreundeten Diener zurück auf deine Hand. Er kostet (2) weniger.',
    image: '/cards/094.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['bounce', 'costreduction']
  },
  {
    id: '095',
    name: 'Seelenopfer',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Zerstört einen deiner Diener und zieht 2 Karten.',
    image: '/cards/095.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['sacrifice', 'draw']
  },
  {
    id: '096',
    name: 'Natursegen',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener +2/+2.',
    image: '/cards/096.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['buff']
  },
  {
    id: '097',
    name: 'Erleuchtung',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ziehe eine Karte. Wenn es ein Zauber ist, kostet er (1) weniger.',
    image: '/cards/097.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['draw', 'conditional', 'costreduction']
  },
  {
    id: '098',
    name: 'Sturmbote',
    cost: 5,
    attack: 6,
    health: 5,
    description: 'Überladung: 1.',
    image: '/cards/098.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['overload']
  },
  {
    id: '099',
    name: 'Finstere Flamme',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 5 Schaden. Heile dich um den verursachten Schaden.',
    image: '/cards/099.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['damage', 'lifesteal']
  },
  {
    id: '100',
    name: 'Klingenruf',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Beschwört zwei 1/1-Klingenlinge mit Eile.',
    image: '/cards/100.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['summon', 'rush']
  }
  {
    id: '101',
    name: 'Macht der Wildnis',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Wähle aus: Gib deinen Dienern +1/+1; oder beschwöre einen 3/2 Panther.',
    image: '/cards/101.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['choice', 'buff', 'summon']
  },
  {
    id: '102',
    name: 'Feuerflamme',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 6 Schaden.',
    image: '/cards/102.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '103',
    name: 'Schild des Lichts',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener Schild.',
    image: '/cards/103.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '104',
    name: 'Todeshauch',
    cost: 5,
    attack: 5,
    health: 6,
    description: 'Todesröcheln: Fügt allen Gegnern 2 Schaden zu.',
    image: '/cards/104.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['deathrattle', 'damage']
  },
  {
    id: '105',
    name: 'Nebelwolf',
    cost: 3,
    attack: 2,
    health: 3,
    description: 'Erhält +1 Angriff für jeden anderen befreundeten Diener.',
    image: '/cards/105.jpg',
    class: 'Waldhüter',
    rarity: 'rare',
    mechanics: ['scaling']
  },
  {
    id: '106',
    name: 'Schattengebet',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Heilt 3 Leben. Wenn der Charakter voll ist, ziehe eine Karte.',
    image: '/cards/106.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['healing', 'draw', 'conditional']
  },
  {
    id: '107',
    name: 'Sturmbrecher',
    cost: 4,
    attack: 4,
    health: 4,
    description: 'Überladung: 2. Kampfschrei: Verursacht 3 Schaden.',
    image: '/cards/107.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['battlecry', 'damage', 'overload']
  },
  {
    id: '108',
    name: 'Heilige Aegis',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Gibt einem Diener Schild und +2 Leben.',
    image: '/cards/108.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['taunt', 'buff']
  },
  {
    id: '109',
    name: 'Knochenritual',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Opfere einen Diener. Erhalte +2 Mana für diesen Zug.',
    image: '/cards/109.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['sacrifice', 'manaboost']
  },
  {
    id: '110',
    name: 'Flammenwirbel',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen Feinden.',
    image: '/cards/110.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '111',
    name: 'Dunkelklinge',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Verborgensein. Gift.',
    image: '/cards/111.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['stealth', 'poisonous']
  },
  {
    id: '112',
    name: 'Mondsegen',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Heilt 4 Leben und zieht eine Karte.',
    image: '/cards/112.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['healing', 'draw']
  },
  {
    id: '113',
    name: 'Donnerzorn',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Windzorn. Überladung: 1.',
    image: '/cards/113.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['windfury', 'overload']
  },
  {
    id: '114',
    name: 'Schattengeist',
    cost: 3,
    attack: 2,
    health: 3,
    description: 'Todesröcheln: Ziehe eine Karte.',
    image: '/cards/114.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['deathrattle', 'draw']
  },
  {
    id: '115',
    name: 'Klingenparade',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener Eile.',
    image: '/cards/115.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '116',
    name: 'Eiskristall',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Friert einen Gegner ein.',
    image: '/cards/116.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['freeze']
  },
  {
    id: '117',
    name: 'Runengeborener',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Zauberschaden +1.',
    image: '/cards/117.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '118',
    name: 'Lichtpionier',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Kampfschrei: Heilt 2 Leben.',
    image: '/cards/118.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['battlecry', 'healing']
  },
  {
    id: '119',
    name: 'Wildwuchs',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Erhalte 1 leeres Manakristall.',
    image: '/cards/119.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['managain']
  },
  {
    id: '120',
    name: 'Krähenfluch',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden. Wenn der Gegner ein Tier ist, +2.',
    image: '/cards/120.jpg',
    class: 'Waldhüter',
    rarity: 'rare',
    mechanics: ['damage', 'conditional']
  }
  {
    id: '121',
    name: 'Gletscherfaust',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Friert getroffene Gegner ein.',
    image: '/cards/121.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['freeze']
  },
  {
    id: '122',
    name: 'Kettenblitz',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Fügt einem Gegner 3 Schaden zu. Springt auf zwei weitere über.',
    image: '/cards/122.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['damage', 'bounce']
  },
  {
    id: '123',
    name: 'Heiliger Zorn',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Fügt einem Gegner 2 Schaden zu. Zieht eine Karte.',
    image: '/cards/123.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['damage', 'draw']
  },
  {
    id: '124',
    name: 'Seelenstrudel',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Zieht eine Karte. Verliere 2 Leben.',
    image: '/cards/124.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['draw', 'lifeloss']
  },
  {
    id: '125',
    name: 'Waldläuferin',
    cost: 1,
    attack: 2,
    health: 1,
    description: 'Eile',
    image: '/cards/125.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '126',
    name: 'Giftige Dagger',
    cost: 2,
    attack: 1,
    health: 0,
    description: 'Deine Angriffe haben Gift.',
    image: '/cards/126.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['poisonous']
  },
  {
    id: '127',
    name: 'Stille',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Setzt alle Effekte eines Dieners zurück.',
    image: '/cards/127.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['silence']
  },
  {
    id: '128',
    name: 'Naturgewalt',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Beschwört zwei 2/2 Treants mit Eile.',
    image: '/cards/128.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['summon', 'rush']
  },
  {
    id: '129',
    name: 'Heiliges Urteil',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Zerstört einen zufälligen feindlichen Diener.',
    image: '/cards/129.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['destroy']
  },
  {
    id: '130',
    name: 'Donnerlanze',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Überladung: 1. Kampfschrei: Zieht eine Karte.',
    image: '/cards/130.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['battlecry', 'draw', 'overload']
  },
  {
    id: '131',
    name: 'Nachtklaue',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Verborgensein',
    image: '/cards/131.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '132',
    name: 'Lichtaura',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Alle befreundeten Diener erhalten +1/+1.',
    image: '/cards/132.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['buff']
  },
  {
    id: '133',
    name: 'Seelenfeuer',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 4 Schaden. Wirft eine zufällige Karte ab.',
    image: '/cards/133.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['damage', 'discard']
  },
  {
    id: '134',
    name: 'Mondbär',
    cost: 3,
    attack: 3,
    health: 5,
    description: 'Schild',
    image: '/cards/134.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '135',
    name: 'Lichtpfeil',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden. Heilt 1 Leben.',
    image: '/cards/135.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['damage', 'healing']
  },
  {
    id: '136',
    name: 'Späher der Wälder',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Ziehe eine Karte.',
    image: '/cards/136.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['draw', 'battlecry']
  },
  {
    id: '137',
    name: 'Finsterer Fluch',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Der Gegner verliert 3 Leben und eine zufällige Karte.',
    image: '/cards/137.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['lifeloss', 'discard']
  },
  {
    id: '138',
    name: 'Schmetterer',
    cost: 3,
    attack: 4,
    health: 4,
    description: 'Kann in diesem Zug nicht angreifen.',
    image: '/cards/138.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['summoningSickness']
  },
  {
    id: '139',
    name: 'Blutrausch',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Deine Diener erhalten +3 Angriff.',
    image: '/cards/139.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['buff']
  },
  {
    id: '140',
    name: 'Echoschatten',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Verborgensein. Zauberschaden +1.',
    image: '/cards/140.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['stealth', 'spellpower']
  }
  {
    id: '141',
    name: 'Manabrunnensucher',
    cost: 2,
    attack: 1,
    health: 3,
    description: 'Kampfschrei: Erhalte +1 Mana-Kristall in diesem Zug.',
    image: '/cards/141.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['battlecry', 'manaboost']
  },
  {
    id: '142',
    name: 'Waldstachel',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Giftig',
    image: '/cards/142.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['poisonous']
  },
  {
    id: '143',
    name: 'Runenwächter',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Zauberschaden +1',
    image: '/cards/143.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '144',
    name: 'Lichtschwinge',
    cost: 4,
    attack: 4,
    health: 5,
    description: 'Immer wenn du heilst, erhält sie +1/+1.',
    image: '/cards/144.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['buff', 'trigger']
  },
  {
    id: '145',
    name: 'Felswächter',
    cost: 3,
    attack: 3,
    health: 6,
    description: 'Schild',
    image: '/cards/145.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '146',
    name: 'Gedankendieb',
    cost: 2,
    attack: 1,
    health: 2,
    description: 'Kampfschrei: Kopiere eine Karte aus der Hand des Gegners.',
    image: '/cards/146.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['battlecry', 'copy']
  },
  {
    id: '147',
    name: 'Tiefenwoge',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Füge allen Feinden 2 Schaden zu.',
    image: '/cards/147.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '148',
    name: 'Schattengabe',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Gibt einem Diener „Verborgensein“.',
    image: '/cards/148.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '149',
    name: 'Tarnassischer Greif',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Eile. Schild.',
    image: '/cards/149.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['rush', 'taunt']
  },
  {
    id: '150',
    name: 'Elementarfunke',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Zauberschaden +1',
    image: '/cards/150.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '151',
    name: 'Klingentänzer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Eile',
    image: '/cards/151.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '152',
    name: 'Totemrufer',
    cost: 3,
    attack: 0,
    health: 4,
    description: 'Zieht am Ende des Zuges ein zufälliges Totem.',
    image: '/cards/152.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['summon', 'endOfTurn']
  },
  {
    id: '153',
    name: 'Seelenfänger',
    cost: 4,
    attack: 4,
    health: 3,
    description: 'Kampfschrei: Zieht eine Karte, verliert 2 Leben.',
    image: '/cards/153.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['draw', 'lifeloss']
  },
  {
    id: '154',
    name: 'Wurzelgebunden',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ein feindlicher Diener kann im nächsten Zug nicht angreifen.',
    image: '/cards/154.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['freeze']
  },
  {
    id: '155',
    name: 'Heilige Woge',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Stellt 4 Leben wieder her.',
    image: '/cards/155.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['healing']
  },
  {
    id: '156',
    name: 'Splittersturm',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Fügt allen Charakteren 3 Schaden zu.',
    image: '/cards/156.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '157',
    name: 'Nachtjägerin',
    cost: 3,
    attack: 3,
    health: 2,
    description: 'Verborgensein',
    image: '/cards/157.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '158',
    name: 'Stahlpanzer',
    cost: 5,
    attack: 5,
    health: 6,
    description: 'Schild',
    image: '/cards/158.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '159',
    name: 'Traumfänger',
    cost: 2,
    attack: 1,
    health: 4,
    description: 'Schlafende Feinde verlieren 1 Leben pro Zug.',
    image: '/cards/159.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['dot', 'sleep']
  },
  {
    id: '160',
    name: 'Kettenschild',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Gibt einem Diener Schild.',
    image: '/cards/160.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  }
  {
    id: '161',
    name: 'Blitzzunge',
    cost: 2,
    attack: 0,
    health: 3,
    description: 'Totems neben diesem erhalten +2 Angriff.',
    image: '/cards/161.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['buff', 'totem']
  },
  {
    id: '162',
    name: 'Dorndiener',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Schild',
    image: '/cards/162.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '163',
    name: 'Dunkelpriesterin',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Kampfschrei: Stellt 3 Leben wieder her.',
    image: '/cards/163.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['battlecry', 'healing']
  },
  {
    id: '164',
    name: 'Wetterkontrolle',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Füge einem Feind 3 Schaden zu.',
    image: '/cards/164.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['damage', 'targeted']
  },
  {
    id: '165',
    name: 'Splitterregen',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Füge zwei zufälligen Feinden je 3 Schaden zu.',
    image: '/cards/165.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['random', 'damage']
  },
  {
    id: '166',
    name: 'Dämonischer Lehrling',
    cost: 1,
    attack: 2,
    health: 1,
    description: '',
    image: '/cards/166.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '167',
    name: 'Magmabinder',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Zauberschaden +1',
    image: '/cards/167.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '168',
    name: 'Frostklaue',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Einfrieren: Ziele kann nächste Runde nicht angreifen.',
    image: '/cards/168.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['freeze']
  },
  {
    id: '169',
    name: 'Siegelbrecherin',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Kampfschrei: Zerstört ein gegnerisches Schild.',
    image: '/cards/169.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'silence']
  },
  {
    id: '170',
    name: 'Vollstrecker der Leere',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Schild',
    image: '/cards/170.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '171',
    name: 'Sturmschlag',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Fügt allen Feinden 4 Schaden zu.',
    image: '/cards/171.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '172',
    name: 'Weg der Schatten',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener Verborgensein.',
    image: '/cards/172.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '173',
    name: 'Heiliger Ruf',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Zerstört alle feindlichen Diener mit Angriff ≤ 2.',
    image: '/cards/173.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['removal']
  },
  {
    id: '174',
    name: 'Flammengeist',
    cost: 2,
    attack: 3,
    health: 2,
    description: '',
    image: '/cards/174.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '175',
    name: 'Schlangenfalle',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Geheimnis: Wenn ein Diener angegriffen wird, beschwöre drei 1/1 Schlangen.',
    image: '/cards/175.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['secret', 'summon']
  },
  {
    id: '176',
    name: 'Astralwandlerin',
    cost: 4,
    attack: 2,
    health: 5,
    description: 'Verborgensein. Wenn sie angreift: Ziehe eine Karte.',
    image: '/cards/176.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['stealth', 'draw']
  },
  {
    id: '177',
    name: 'Seelenritt',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ziehe 2 Karten und verliere 2 Leben.',
    image: '/cards/177.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['draw', 'lifeloss']
  },
  {
    id: '178',
    name: 'Totemgolem',
    cost: 2,
    attack: 3,
    health: 4,
    description: 'Überladung: (1)',
    image: '/cards/178.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['overload']
  },
  {
    id: '179',
    name: 'Naturgewalt',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Beschwört zwei 2/2 Wurzeln mit Eile.',
    image: '/cards/179.jpg',
    class: 'Naturrufer',
    rarity: 'epic',
    mechanics: ['summon', 'rush']
  },
  {
    id: '180',
    name: 'Kristallformung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Wähle: +2 Angriff oder +2 Leben.',
    image: '/cards/180.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['choice', 'buff']
  }
  {
    id: '181',
    name: 'Klingenwirbel',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Fügt allen feindlichen Dienern 1 Schaden zu. Pro Karte im Deck +1 Schaden.',
    image: '/cards/181.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['aoe', 'scaling']
  },
  {
    id: '182',
    name: 'Manaschub',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Erhalte 1 zusätzliches Mana nur in diesem Zug.',
    image: '/cards/182.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['mana']
  },
  {
    id: '183',
    name: 'Wellenformer',
    cost: 5,
    attack: 4,
    health: 5,
    description: 'Kampfschrei: Verstärkt Zauber um +1 Schaden.',
    image: '/cards/183.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['battlecry', 'spellpower']
  },
  {
    id: '184',
    name: 'Gedankenklaue',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Kopiere einen Zauber aus der Hand des Gegners.',
    image: '/cards/184.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['copy']
  },
  {
    id: '185',
    name: 'Lichtsegen',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Stellt bei einem Charakter 6 Leben wieder her.',
    image: '/cards/185.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['healing']
  },
  {
    id: '186',
    name: 'Feuerkrähe',
    cost: 1,
    attack: 2,
    health: 1,
    description: '',
    image: '/cards/186.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '187',
    name: 'Seelensog',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Zerstört einen Diener. Dein Held erleidet 3 Schaden.',
    image: '/cards/187.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['destroy', 'lifeloss']
  },
  {
    id: '188',
    name: 'Runenrüstung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Erhalte 5 Rüstung.',
    image: '/cards/188.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['armor']
  },
  {
    id: '189',
    name: 'Knochenspuk',
    cost: 5,
    attack: 2,
    health: 6,
    description: 'Schild',
    image: '/cards/189.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '190',
    name: 'Felsformer',
    cost: 4,
    attack: 3,
    health: 3,
    description: 'Kampfschrei: Verleiht einem Verbündeten +3 Leben.',
    image: '/cards/190.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'buff']
  },
  {
    id: '191',
    name: 'Klingenregen',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Fügt allen Feinden 2 Schaden zu und zieht eine Karte.',
    image: '/cards/191.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['aoe', 'draw']
  },
  {
    id: '192',
    name: 'Doppeltes Spiel',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Wenn ein Diener stirbt, beschwöre eine Kopie davon.',
    image: '/cards/192.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['deathrattle', 'summon']
  },
  {
    id: '193',
    name: 'Waldläuferin',
    cost: 3,
    attack: 3,
    health: 2,
    description: 'Kampfschrei: Fügt einem Feind 2 Schaden zu.',
    image: '/cards/193.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['battlecry', 'damage']
  },
  {
    id: '194',
    name: 'Blutrausch',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Verleiht allen Dienern +3 Angriff in diesem Zug.',
    image: '/cards/194.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['buff']
  },
  {
    id: '195',
    name: 'Klingenakrobat',
    cost: 2,
    attack: 3,
    health: 1,
    description: '',
    image: '/cards/195.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '196',
    name: 'Sturmrufer',
    cost: 5,
    attack: 4,
    health: 6,
    description: 'Zauberschaden +1',
    image: '/cards/196.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '197',
    name: 'Schattengeister',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Beschwört zwei 2/2 Schattenwesen.',
    image: '/cards/197.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['summon']
  },
  {
    id: '198',
    name: 'Seelenbrand',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Fügt einem Ziel 4 Schaden zu. Zerstört eine deiner Karten.',
    image: '/cards/198.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['damage', 'sacrifice']
  },
  {
    id: '199',
    name: 'Stahlbiss',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Schild',
    image: '/cards/199.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '200',
    name: 'Segen der Flamme',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener +3 Angriff.',
    image: '/cards/200.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['buff']
  }
  {
    id: '201',
    name: 'Mondlichtsegen',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener +2 Leben.',
    image: '/cards/201.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['buff']
  },
  {
    id: '202',
    name: 'Wilde Pranke',
    cost: 2,
    attack: 3,
    health: 2,
    description: '',
    image: '/cards/202.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '203',
    name: 'Manablitz',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Erhalte 2 Mana-Kristalle in diesem Zug.',
    image: '/cards/203.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['mana']
  },
  {
    id: '204',
    name: 'Blutschwur',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Zieht 3 Karten. Euer Held verliert 3 Leben.',
    image: '/cards/204.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['draw', 'lifeloss']
  },
  {
    id: '205',
    name: 'Eiserner Schildträger',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Schild',
    image: '/cards/205.jpg',
    class: 'neutral',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '206',
    name: 'Zwillingsschläge',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Fügt zwei zufälligen Feinden je 3 Schaden zu.',
    image: '/cards/206.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['damage']
  },
  {
    id: '207',
    name: 'Wurzelwache',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Schild',
    image: '/cards/207.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '208',
    name: 'Sturmkrähe',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Windzorn',
    image: '/cards/208.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['windfury']
  },
  {
    id: '209',
    name: 'Schattenkuss',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Fügt einem Diener 2 Schaden zu und heilt Euren Helden um 2.',
    image: '/cards/209.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['damage', 'heal']
  },
  {
    id: '210',
    name: 'Lichtschildmagierin',
    cost: 3,
    attack: 3,
    health: 4,
    description: '',
    image: '/cards/210.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '211',
    name: 'Flammenzunge',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Euer Zauber verursacht in diesem Zug +2 Schaden.',
    image: '/cards/211.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['spellpower']
  },
  {
    id: '212',
    name: 'Klingenrüstung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Erhaltet 6 Rüstung.',
    image: '/cards/212.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['armor']
  },
  {
    id: '213',
    name: 'Manaschild',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Blockt die nächsten 3 Schaden, die Euer Held erhalten würde.',
    image: '/cards/213.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['shield']
  },
  {
    id: '214',
    name: 'Seelenfeuer',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Fügt einem Ziel 4 Schaden zu. Verliert eine zufällige Karte.',
    image: '/cards/214.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['damage', 'discard']
  },
  {
    id: '215',
    name: 'Blitzgeschmiedeter',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Zauberschaden +1',
    image: '/cards/215.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '216',
    name: 'Waldstreuner',
    cost: 1,
    attack: 2,
    health: 1,
    description: '',
    image: '/cards/216.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '217',
    name: 'Runenbann',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Stille einen Diener.',
    image: '/cards/217.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['silence']
  },
  {
    id: '218',
    name: 'Wellenreiter',
    cost: 4,
    attack: 5,
    health: 4,
    description: '',
    image: '/cards/218.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '219',
    name: 'Feuerling',
    cost: 1,
    attack: 2,
    health: 1,
    description: '',
    image: '/cards/219.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '220',
    name: 'Wächter des Waldes',
    cost: 6,
    attack: 6,
    health: 7,
    description: 'Schild',
    image: '/cards/220.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '221',
    name: 'Flammenkralle',
    cost: 1,
    attack: 3,
    health: 1,
    description: '',
    image: '/cards/221.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '222',
    name: 'Seelensplitter',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Fügt 2 Schaden zu. Heilt Euren Helden um 2.',
    image: '/cards/222.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['damage', 'heal']
  },
  {
    id: '223',
    name: 'Blitzkralle',
    cost: 4,
    attack: 4,
    health: 2,
    description: 'Windzorn',
    image: '/cards/223.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '224',
    name: 'Waldgeistbiss',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Fügt einem feindlichen Diener 4 Schaden zu.',
    image: '/cards/224.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '225',
    name: 'Rüstungsschlag',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden. Wenn Ihr Rüstung habt, 4 Schaden.',
    image: '/cards/225.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['damage', 'conditional']
  },
  {
    id: '226',
    name: 'Flammenregen',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Fügt allen Dienern 3 Schaden zu.',
    image: '/cards/226.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['aoe']
  },
  {
    id: '227',
    name: 'Dunkelberührung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Zufälliger feindlicher Diener wird zerstört.',
    image: '/cards/227.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['destroy']
  },
  {
    id: '228',
    name: 'Waldheiler',
    cost: 3,
    attack: 2,
    health: 4,
    description: 'Kampfschrei: Stellt 4 Leben wieder her.',
    image: '/cards/228.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['battlecry', 'healing']
  },
  {
    id: '229',
    name: 'Ritualklinge',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Heilt Euren Helden beim Angriff.',
    image: '/cards/229.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['lifesteal']
  },
  {
    id: '230',
    name: 'Wutsturm',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Fügt allen Gegnern 4 Schaden zu.',
    image: '/cards/230.jpg',
    class: 'Klingenmeister',
    rarity: 'epic',
    mechanics: ['aoe']
  },
  {
    id: '231',
    name: 'Windgeist',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Windzorn',
    image: '/cards/231.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['windfury']
  },
  {
    id: '232',
    name: 'Mondrufer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Zauberschaden +1',
    image: '/cards/232.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '233',
    name: 'Gedankensog',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Zieht zwei Karten. Der Gegner zieht auch eine.',
    image: '/cards/233.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['draw']
  },
  {
    id: '234',
    name: 'Elementarfunke',
    cost: 1,
    attack: 2,
    health: 1,
    description: '',
    image: '/cards/234.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '235',
    name: 'Naturwächter',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Schild',
    image: '/cards/235.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '236',
    name: 'Klingenpirscher',
    cost: 2,
    attack: 3,
    health: 2,
    description: '',
    image: '/cards/236.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: []
  },
  {
    id: '237',
    name: 'Sturmzauber',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Fügt 5 Schaden zufällig auf Gegner aufgeteilt zu.',
    image: '/cards/237.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['aoe']
  },
  {
    id: '238',
    name: 'Wellenformer',
    cost: 2,
    attack: 1,
    health: 3,
    description: 'Zauberschaden +1',
    image: '/cards/238.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '239',
    name: 'Klingenmagier',
    cost: 4,
    attack: 4,
    health: 2,
    description: 'Euer Held erhält +1 Angriff in diesem Zug.',
    image: '/cards/239.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['buff']
  },
  {
    id: '240',
    name: 'Letzter Funken',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Fügt allen Charakteren 3 Schaden zu.',
    image: '/cards/240.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['aoe']
  }



];
