// ⚡ AUTOGENERIERT – NICHT BEARBEITEN (run GitHub Action to update)\n
export type CardData = { id: string; name: string; cost: number; attack: number; health: number; description: string; image: string; class: string; rarity: 'common' | 'rare' | 'epic' | 'legendary'; mechanics?: string[] };

export const allCards: CardData[] = [
  {
    "id": "000",
    "name": "Waldhauch",
    "cost": 5,
    "attack": 0,
    "health": 0,
    "description": "Deal $8 damage to a minion.",
    "image": "/cards/000.jpg",
    "class": "Elementarwirker",
    "rarity": "common"
  },
  {
    "id": "001",
    "name": "Rindenhaut‑Schützer",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Secret: When a friendly minion dies, summon a random minion with the same Cost.",
    "image": "/cards/001.jpg",
    "class": "Elementarwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "002",
    "name": "Lebenswurzel",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Your Hero Power deals 1 extra damage.",
    "image": "/cards/002.jpg",
    "class": "Elementarwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "003",
    "name": "Zornklinge",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Deal $2 damage to a minion. This spell gets double bonus from Spell Damage.",
    "image": "/cards/003.jpg",
    "class": "Elementarwirker",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "004",
    "name": "Magmaschlag",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Transform a minion into a 4/2 Boar with Charge.",
    "image": "/cards/004.jpg",
    "class": "Elementarwirker",
    "rarity": "rare"
  },
  {
    "id": "005",
    "name": "Lichtnova",
    "cost": 4,
    "attack": 3,
    "health": 5,
    "description": "Inspire: Gain Spell Damage +1.",
    "image": "/cards/005.jpg",
    "class": "Elementarwirker",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "006",
    "name": "Schattengeist",
    "cost": 3,
    "attack": 3,
    "health": 4,
    "description": "Battlecry: Add a random spell to each player's hand.",
    "image": "/cards/006.jpg",
    "class": "Elementarwirker",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "007",
    "name": "Windwandler",
    "cost": 6,
    "attack": 6,
    "health": 6,
    "description": "You can use your Hero Power any number of times.",
    "image": "/cards/007.jpg",
    "class": "Elementarwirker",
    "rarity": "epic"
  },
  {
    "id": "008",
    "name": "Klingenhexe",
    "cost": 8,
    "attack": 7,
    "health": 7,
    "description": "Deathrattle: Add 3 copies of Arcane Missiles to your hand.",
    "image": "/cards/008.jpg",
    "class": "Elementarwirker",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "009",
    "name": "Auge des Waldes",
    "cost": 5,
    "attack": 3,
    "health": 3,
    "description": "Battlecry: If you have a Beast, summon a\nrandom Beast.",
    "image": "/cards/009.jpg",
    "class": "Waldhüter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "010",
    "name": "Dämonenstoß",
    "cost": 4,
    "attack": 3,
    "health": 5,
    "description": "Whenever a character is healed, gain +2 Attack.",
    "image": "/cards/010.jpg",
    "class": "Schattenwirker",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "011",
    "name": "Kristallheiler",
    "cost": 4,
    "attack": 5,
    "health": 4,
    "description": "Inspire: Deal 4 damage to each hero.",
    "image": "/cards/011.jpg",
    "class": "Schattenwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "012",
    "name": "Nebelkrieger",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Choose a minion. Whenever it attacks, restore 4 Health to\nyour hero.",
    "image": "/cards/012.jpg",
    "class": "Schattenwirker",
    "rarity": "common"
  },
  {
    "id": "013",
    "name": "Runenwächter",
    "cost": 3,
    "attack": 3,
    "health": 3,
    "description": "Whenever you draw a card, reduce its Cost by (1).",
    "image": "/cards/013.jpg",
    "class": "Schattenwirker",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "014",
    "name": "Flammenbote",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Put a copy of an enemy minion into your hand.",
    "image": "/cards/014.jpg",
    "class": "Schattenwirker",
    "rarity": "rare"
  },
  {
    "id": "015",
    "name": "Todeshauch",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Swap the Attack and Health of all minions.",
    "image": "/cards/015.jpg",
    "class": "Schattenwirker",
    "rarity": "epic"
  },
  {
    "id": "016",
    "name": "Seelenbrenner",
    "cost": 4,
    "attack": 2,
    "health": 6,
    "description": "Battlecry: If you're holding a Dragon, gain +1 Attack and Taunt.",
    "image": "/cards/016.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "017",
    "name": "Donnerfaust",
    "cost": 7,
    "attack": 5,
    "health": 4,
    "description": "Inspire: Summon a random Legendary minion.",
    "image": "/cards/017.jpg",
    "class": "Schattenwirker",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "018",
    "name": "Wachposten",
    "cost": 4,
    "attack": 1,
    "health": 1,
    "description": "Deathrattle: At the end\n of the turn, summon a Dreadsteed.",
    "image": "/cards/018.jpg",
    "class": "Seelenmeister",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "019",
    "name": "Lichtfunken",
    "cost": 7,
    "attack": 6,
    "health": 8,
    "description": "",
    "image": "/cards/019.jpg",
    "class": "Seelenmeister",
    "rarity": "common"
  },
  {
    "id": "020",
    "name": "Seelensucher",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Whenever you discard a card, gain +1/+1.",
    "image": "/cards/020.jpg",
    "class": "Seelenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "021",
    "name": "Naturpfad",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "When you play or discard this, deal $4 damage to a random enemy.",
    "image": "/cards/021.jpg",
    "class": "Seelenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "022",
    "name": "Stahlfalke",
    "cost": 6,
    "attack": 5,
    "health": 4,
    "description": "Inspire: Destroy a random minion for each player.",
    "image": "/cards/022.jpg",
    "class": "Seelenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "023",
    "name": "Schattenflamme",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Give a Demon +3/+3. Give your opponent a Mana Crystal.",
    "image": "/cards/023.jpg",
    "class": "Seelenmeister",
    "rarity": "common"
  },
  {
    "id": "024",
    "name": "Runenschlag",
    "cost": 6,
    "attack": 0,
    "health": 0,
    "description": "Destroy 2 random enemy minions. Discard 2 random cards.",
    "image": "/cards/024.jpg",
    "class": "Seelenmeister",
    "rarity": "epic"
  },
  {
    "id": "025",
    "name": "Windgeheul",
    "cost": 2,
    "attack": 4,
    "health": 3,
    "description": "Whenever this minion takes damage, also deal that amount to your hero.",
    "image": "/cards/025.jpg",
    "class": "Seelenmeister",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "026",
    "name": "Splitterklinge",
    "cost": 6,
    "attack": 4,
    "health": 4,
    "description": "Cards you draw from your Hero Power cost (0).",
    "image": "/cards/026.jpg",
    "class": "Seelenmeister",
    "rarity": "legendary"
  },
  {
    "id": "027",
    "name": "Glanzschild‑Wächter",
    "cost": 5,
    "attack": 3,
    "health": 7,
    "description": "Combo: Gain +3 Attack.",
    "image": "/cards/027.jpg",
    "class": "Klingenläufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "028",
    "name": "Dunkelpriester",
    "cost": 1,
    "attack": 2,
    "health": 1,
    "description": "Whenever you equip a weapon, give it +1 Attack.",
    "image": "/cards/028.jpg",
    "class": "Klingenläufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "029",
    "name": "Flammenschlag",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Combo: Deal 1 damage.",
    "image": "/cards/029.jpg",
    "class": "Klingenläufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "030",
    "name": "Pfadfinder",
    "cost": 2,
    "attack": 2,
    "health": 2,
    "description": "Whenever this minion attacks a hero, add the Coin to your hand.",
    "image": "/cards/030.jpg",
    "class": "Klingenläufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "031",
    "name": "Energiedieb",
    "cost": 3,
    "attack": 4,
    "health": 3,
    "description": "Battlecry: If you have a Pirate, gain +1/+1.",
    "image": "/cards/031.jpg",
    "class": "Klingenläufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "032",
    "name": "Wurzelkoloss",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Add 2 random cards to your hand (from your opponent's class).",
    "image": "/cards/032.jpg",
    "class": "Klingenläufer",
    "rarity": "rare"
  },
  {
    "id": "033",
    "name": "Dämonisches Feuer",
    "cost": 4,
    "attack": 1,
    "health": 0,
    "description": "Your Hero Power gives this weapon +1 Attack instead of replacing it.",
    "image": "/cards/033.jpg",
    "class": "Klingenläufer",
    "rarity": "epic"
  },
  {
    "id": "034",
    "name": "Schildsänger",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Shuffle 3 Ambushes into your opponent's deck. When drawn, you summon a 4/4 Nerubian.",
    "image": "/cards/034.jpg",
    "class": "Klingenläufer",
    "rarity": "epic"
  },
  {
    "id": "035",
    "name": "Donnerzorn",
    "cost": 9,
    "attack": 8,
    "health": 4,
    "description": "Deathrattle: Return this to your hand and summon a 4/4 Nerubian.",
    "image": "/cards/035.jpg",
    "class": "Klingenläufer",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "036",
    "name": "Dämmerungsmagier",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Choose One - Deal $2 damage; or Summon two 1/1 Saplings.",
    "image": "/cards/036.jpg",
    "class": "Naturrufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "037",
    "name": "Waldläuferin",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "Battlecry: Gain an empty Mana Crystal.\nDeathrattle: Lose a Mana Crystal.",
    "image": "/cards/037.jpg",
    "class": "Naturrufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "038",
    "name": "Kettenblitz",
    "cost": 4,
    "attack": 5,
    "health": 4,
    "description": "Inspire: Give your hero\n+2 Attack this turn.",
    "image": "/cards/038.jpg",
    "class": "Naturrufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "039",
    "name": "Schattenläufer",
    "cost": 4,
    "attack": 4,
    "health": 4,
    "description": "Battlecry: Give a friendly Beast +3 Health.",
    "image": "/cards/039.jpg",
    "class": "Naturrufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "040",
    "name": "Kristallformer",
    "cost": 7,
    "attack": 6,
    "health": 6,
    "description": "Whenever you summon a Beast, reduce the Cost of this card by (1).",
    "image": "/cards/040.jpg",
    "class": "Naturrufer",
    "rarity": "rare"
  },
  {
    "id": "041",
    "name": "Echoschlitzer",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "[x]Choose One - Transform\ninto a 2/1 with Charge;\nor a 3/2 with Stealth.",
    "image": "/cards/041.jpg",
    "class": "Naturrufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "042",
    "name": "Lebensweber",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "Gain 10 Mana Crystals. Discard your hand.",
    "image": "/cards/042.jpg",
    "class": "Naturrufer",
    "rarity": "epic"
  },
  {
    "id": "043",
    "name": "Sturmkralle",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Destroy a minion.\nAdd a random minion to your opponent's hand.",
    "image": "/cards/043.jpg",
    "class": "Naturrufer",
    "rarity": "epic"
  },
  {
    "id": "044",
    "name": "Dornenwächter",
    "cost": 9,
    "attack": 5,
    "health": 5,
    "description": "Your minions cost (1).",
    "image": "/cards/044.jpg",
    "class": "Naturrufer",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "045",
    "name": "Dämonenzorn",
    "cost": 3,
    "attack": 3,
    "health": 2,
    "description": "Battlecry: Summon a random basic Totem.",
    "image": "/cards/045.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "046",
    "name": "Frostklinge",
    "cost": 4,
    "attack": 4,
    "health": 4,
    "description": "Battlecry: Gain +1/+1 for each friendly Totem.",
    "image": "/cards/046.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "047",
    "name": "Runenpriester",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Restore #7 Health. Reveal a minion in each deck. If yours costs more, Restore #14 instead.",
    "image": "/cards/047.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare"
  },
  {
    "id": "048",
    "name": "Wurzelranke",
    "cost": 5,
    "attack": 3,
    "health": 6,
    "description": "Inspire: Give your Totems +2 Attack.",
    "image": "/cards/048.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "049",
    "name": "Blutpakt",
    "cost": 4,
    "attack": 2,
    "health": 0,
    "description": "Deathrattle: Your Hero Power becomes 'Deal 2 damage.'",
    "image": "/cards/049.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "050",
    "name": "Lichtformer",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Deal $4-$5 damage to all minions. Overload: (5)",
    "image": "/cards/050.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "051",
    "name": "Tiefenschleicher",
    "cost": 2,
    "attack": 3,
    "health": 4,
    "description": "Overload: (1)",
    "image": "/cards/051.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "052",
    "name": "Dunkelklaue",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Draw 2 cards. Overload: (2)",
    "image": "/cards/052.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "053",
    "name": "Kettenheiler",
    "cost": 6,
    "attack": 4,
    "health": 4,
    "description": "Battlecry: Give all minions in your hand and deck +1/+1.",
    "image": "/cards/053.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "054",
    "name": "Energiefokus",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Restore #5 Health.",
    "image": "/cards/054.jpg",
    "class": "Schattenwirker",
    "rarity": "common"
  },
  {
    "id": "055",
    "name": "Wellenformer",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Deal $2 damage to a minion and the minions next to it.",
    "image": "/cards/055.jpg",
    "class": "Waldhüter",
    "rarity": "rare"
  },
  {
    "id": "056",
    "name": "Funkenschlag",
    "cost": 3,
    "attack": 4,
    "health": 2,
    "description": "Battlecry: Give a friendly Beast Immune this turn.",
    "image": "/cards/056.jpg",
    "class": "Waldhüter",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "057",
    "name": "Geisterrausch",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, draw it.",
    "image": "/cards/057.jpg",
    "class": "Waldhüter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "058",
    "name": "Höllenfeuer",
    "cost": 1,
    "attack": 2,
    "health": 1,
    "description": "Inspire: If your hand is empty, deal 2 damage to the enemy hero.",
    "image": "/cards/058.jpg",
    "class": "Waldhüter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "059",
    "name": "Astralkugel",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Secret: After your hero is attacked, summon a 3/3 Bear with Taunt.",
    "image": "/cards/059.jpg",
    "class": "Waldhüter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "060",
    "name": "Schattenseherin",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Each time you cast a spell this turn, add a random Hunter card to your hand.",
    "image": "/cards/060.jpg",
    "class": "Waldhüter",
    "rarity": "epic"
  },
  {
    "id": "061",
    "name": "Kristallhieb",
    "cost": 6,
    "attack": 0,
    "health": 0,
    "description": "Summon three 1/1 Webspinners.",
    "image": "/cards/061.jpg",
    "class": "Waldhüter",
    "rarity": "rare"
  },
  {
    "id": "062",
    "name": "Urwächter",
    "cost": 7,
    "attack": 4,
    "health": 2,
    "description": "Whenever another minion takes damage, destroy it.",
    "image": "/cards/062.jpg",
    "class": "Waldhüter",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "063",
    "name": "Lichturteil",
    "cost": 3,
    "attack": 4,
    "health": 2,
    "description": "At the end of your turn, deal 1 damage to all other minions.",
    "image": "/cards/063.jpg",
    "class": "Waldhüter",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "064",
    "name": "Splitterklinge (Durchbohren)",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Deal $3 damage.\nGain 3 Armor.",
    "image": "/cards/064.jpg",
    "class": "Klingenmeister",
    "rarity": "common"
  },
  {
    "id": "065",
    "name": "Blutgesang",
    "cost": 3,
    "attack": 3,
    "health": 0,
    "description": "Battlecry: If you have a minion with Taunt, gain +1 Durability.",
    "image": "/cards/065.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "066",
    "name": "Donnerhau",
    "cost": 3,
    "attack": 3,
    "health": 3,
    "description": "Inspire: Give your weapon +1 Attack.",
    "image": "/cards/066.jpg",
    "class": "Klingenmeister",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "067",
    "name": "Waldschleicher",
    "cost": 4,
    "attack": 5,
    "health": 3,
    "description": "Also damages the minions next to whomever\nhe attacks.",
    "image": "/cards/067.jpg",
    "class": "Klingenmeister",
    "rarity": "epic"
  },
  {
    "id": "068",
    "name": "Manaspule",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Give your Taunt minions +2/+2.",
    "image": "/cards/068.jpg",
    "class": "Klingenmeister",
    "rarity": "common"
  },
  {
    "id": "069",
    "name": "Knochengardist",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Taunt\nBattlecry: Give a\nminion Taunt.",
    "image": "/cards/069.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "070",
    "name": "Wurzelnetz",
    "cost": 7,
    "attack": 4,
    "health": 6,
    "description": "Charrrrrge\nCosts (1) less for each friendly Pirate.",
    "image": "/cards/070.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "071",
    "name": "Ritual des Schmerzes",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "Battlecry: If you're holding a Dragon, gain +1 Attack and Charge.",
    "image": "/cards/071.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "072",
    "name": "Funkenpriesterin",
    "cost": 10,
    "attack": 7,
    "health": 7,
    "description": "Battlecry: Draw 3 cards.\nPut any minions you drew directly into the battlefield.",
    "image": "/cards/072.jpg",
    "class": "Klingenmeister",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "073",
    "name": "Klingentänzerin",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Secret: When your turn starts, give your minions +1/+1.",
    "image": "/cards/073.jpg",
    "class": "Lichtwächter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "074",
    "name": "Dunkelmeditation",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Give a minion\n+3 Attack and Divine Shield.",
    "image": "/cards/074.jpg",
    "class": "Lichtwächter",
    "rarity": "common"
  },
  {
    "id": "075",
    "name": "Splitterregen",
    "cost": 3,
    "attack": 2,
    "health": 4,
    "description": "Your Silver Hand Recruits have +1 Attack.",
    "image": "/cards/075.jpg",
    "class": "Lichtwächter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "076",
    "name": "Heilende Aura",
    "cost": 4,
    "attack": 3,
    "health": 4,
    "description": "Inspire: Summon a random Murloc.",
    "image": "/cards/076.jpg",
    "class": "Lichtwächter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "077",
    "name": "Widerstandsschrei",
    "cost": 2,
    "attack": 2,
    "health": 0,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, +1 Durability.",
    "image": "/cards/077.jpg",
    "class": "Lichtwächter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "078",
    "name": "Wacholderbär",
    "cost": 6,
    "attack": 0,
    "health": 0,
    "description": "Destroy all minions except each player's highest Attack minion.",
    "image": "/cards/078.jpg",
    "class": "Lichtwächter",
    "rarity": "epic"
  },
  {
    "id": "079",
    "name": "Blitzritual",
    "cost": 6,
    "attack": 6,
    "health": 6,
    "description": "Battlecry: Put one of each Secret from your deck into the battlefield.",
    "image": "/cards/079.jpg",
    "class": "Lichtwächter",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "080",
    "name": "Zornkrähe",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "You can use your Hero Power twice a turn.",
    "image": "/cards/080.jpg",
    "class": "neutral",
    "rarity": "epic"
  },
  {
    "id": "081",
    "name": "Lichtblitz",
    "cost": 7,
    "attack": 3,
    "health": 7,
    "description": "Battlecry: Change all enemy minions'\nAttack to 1.",
    "image": "/cards/081.jpg",
    "class": "Lichtwächter",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "082",
    "name": "Schattenformer",
    "cost": 1,
    "attack": 1,
    "health": 2,
    "description": "Inspire: Gain +1 Attack.",
    "image": "/cards/082.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "083",
    "name": "Runenstecher",
    "cost": 3,
    "attack": 3,
    "health": 3,
    "description": "Inspire: Gain Windfury\nthis turn.",
    "image": "/cards/083.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "084",
    "name": "Wurzelspeer",
    "cost": 2,
    "attack": 1,
    "health": 2,
    "description": "Battlecry: Give a friendly minion +2 Attack.",
    "image": "/cards/084.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "085",
    "name": "Klingenfurie",
    "cost": 4,
    "attack": 2,
    "health": 6,
    "description": "Your Hero Power costs (1).",
    "image": "/cards/085.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "086",
    "name": "Geisterklaue",
    "cost": 3,
    "attack": 4,
    "health": 3,
    "description": "Battlecry: Your opponent's Hero Power costs (5) more next turn.",
    "image": "/cards/086.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "087",
    "name": "Aegis‑Wächter",
    "cost": 3,
    "attack": 2,
    "health": 1,
    "description": "Charge\nDivine Shield",
    "image": "/cards/087.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "088",
    "name": "Schleiermagie",
    "cost": 6,
    "attack": 8,
    "health": 5,
    "description": "50% chance to attack the wrong enemy.",
    "image": "/cards/088.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "089",
    "name": "Lebensfunke",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Inspire: Gain +1 Health.",
    "image": "/cards/089.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "090",
    "name": "Kriegsbär",
    "cost": 5,
    "attack": 4,
    "health": 3,
    "description": "Inspire: Give your other minions +1/+1.",
    "image": "/cards/090.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "091",
    "name": "Magmaschleuder",
    "cost": 4,
    "attack": 1,
    "health": 8,
    "description": "Inspire: Restore #2 Health to your hero.",
    "image": "/cards/091.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "092",
    "name": "Knochenrüstung",
    "cost": 3,
    "attack": 5,
    "health": 2,
    "description": "",
    "image": "/cards/092.jpg",
    "class": "neutral",
    "rarity": "common"
  },
  {
    "id": "093",
    "name": "Schattenschritt",
    "cost": 4,
    "attack": 2,
    "health": 6,
    "description": "Spell Damage +1",
    "image": "/cards/093.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "094",
    "name": "Seelenopfer",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "Battlecry: Deal 1 damage to a random enemy.",
    "image": "/cards/094.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "095",
    "name": "Natursegen",
    "cost": 3,
    "attack": 2,
    "health": 2,
    "description": "Stealth\nDivine Shield",
    "image": "/cards/095.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "096",
    "name": "Erleuchtung",
    "cost": 5,
    "attack": 5,
    "health": 5,
    "description": "Battlecry: Give a friendly Mech +1/+1.",
    "image": "/cards/096.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "097",
    "name": "Sturmbote",
    "cost": 1,
    "attack": 2,
    "health": 1,
    "description": "Taunt",
    "image": "/cards/097.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "098",
    "name": "Finstere Flamme",
    "cost": 6,
    "attack": 6,
    "health": 5,
    "description": "Battlecry: Copy your opponent's Hero Power.",
    "image": "/cards/098.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "099",
    "name": "Klingenruf",
    "cost": 6,
    "attack": 3,
    "health": 5,
    "description": "Inspire: Summon a 3/5 War Kodo.",
    "image": "/cards/099.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "100",
    "name": "Macht der Wildnis",
    "cost": 3,
    "attack": 3,
    "health": 3,
    "description": "Inspire: Summon a 1/1 Silver Hand Recruit.",
    "image": "/cards/100.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "101",
    "name": "Feuerflamme",
    "cost": 5,
    "attack": 5,
    "health": 6,
    "description": "",
    "image": "/cards/101.jpg",
    "class": "neutral",
    "rarity": "common"
  },
  {
    "id": "102",
    "name": "Schild des Lichts",
    "cost": 7,
    "attack": 5,
    "health": 9,
    "description": "",
    "image": "/cards/102.jpg",
    "class": "neutral",
    "rarity": "common"
  },
  {
    "id": "103",
    "name": "Todeshauch (Variante)",
    "cost": 9,
    "attack": 9,
    "health": 7,
    "description": "Battlecry: Deal 4 damage.",
    "image": "/cards/103.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "104",
    "name": "Nebelwolf",
    "cost": 5,
    "attack": 5,
    "health": 5,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, restore #7 Health to your hero.",
    "image": "/cards/104.jpg",
    "class": "Lichtwächter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "105",
    "name": "Schattengebet",
    "cost": 1,
    "attack": 2,
    "health": 4,
    "description": "Battlecry: Deal 3 damage to this minion.",
    "image": "/cards/105.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "106",
    "name": "Sturmbrecher",
    "cost": 3,
    "attack": 4,
    "health": 3,
    "description": "Battlecry: Silence a Demon.",
    "image": "/cards/106.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "107",
    "name": "Heilige Aegis",
    "cost": 4,
    "attack": 5,
    "health": 3,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, gain Charge.",
    "image": "/cards/107.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "108",
    "name": "Knochenritual",
    "cost": 2,
    "attack": 2,
    "health": 4,
    "description": "Can't attack.\nInspire: Can attack as normal this turn.",
    "image": "/cards/108.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "109",
    "name": "Flammenwirbel",
    "cost": 3,
    "attack": 2,
    "health": 5,
    "description": "Inspire: Return this minion to your hand.",
    "image": "/cards/109.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "110",
    "name": "Dunkelklinge (Gift)",
    "cost": 4,
    "attack": 3,
    "health": 5,
    "description": "Battlecry: Restore #4 Health to each hero.",
    "image": "/cards/110.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "111",
    "name": "Mondsegen",
    "cost": 6,
    "attack": 5,
    "health": 6,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, gain Taunt and Divine Shield.",
    "image": "/cards/111.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "112",
    "name": "Donnerzorn (Variante)",
    "cost": 5,
    "attack": 5,
    "health": 4,
    "description": "Inspire: Add a 2/2 Squire to your hand.",
    "image": "/cards/112.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "113",
    "name": "Schattengeist (Variante)",
    "cost": 4,
    "attack": 5,
    "health": 4,
    "description": "Taunt",
    "image": "/cards/113.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "114",
    "name": "Klingenparade",
    "cost": 3,
    "attack": 2,
    "health": 2,
    "description": "Battlecry: The next time you use your Hero Power, it costs (2) less.",
    "image": "/cards/114.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "115",
    "name": "Eiskristall",
    "cost": 2,
    "attack": 1,
    "health": 4,
    "description": "Battlecry: If you're holding a Dragon, gain +1 Attack and Taunt.",
    "image": "/cards/115.jpg",
    "class": "Schattenwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "116",
    "name": "Runengeborener",
    "cost": 3,
    "attack": 4,
    "health": 2,
    "description": "Battlecry: If you have a minion with Spell Damage, gain +2/+2.",
    "image": "/cards/116.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "117",
    "name": "Lichtpionier",
    "cost": 6,
    "attack": 5,
    "health": 5,
    "description": "Battlecry: Add a random Paladin card to your hand.",
    "image": "/cards/117.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "118",
    "name": "Wildwuchs",
    "cost": 5,
    "attack": 4,
    "health": 4,
    "description": "Inspire: Gain +2/+2.",
    "image": "/cards/118.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "119",
    "name": "Krähenfluch",
    "cost": 10,
    "attack": 8,
    "health": 8,
    "description": "Costs (1) less for each time you used your Hero Power this game.",
    "image": "/cards/119.jpg",
    "class": "neutral",
    "rarity": "epic"
  },
  {
    "id": "120",
    "name": "Gletscherfaust",
    "cost": 4,
    "attack": 4,
    "health": 4,
    "description": "Whenever you play a card with Battlecry, gain +1/+1.",
    "image": "/cards/120.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "121",
    "name": "Kettenblitz (Variante)",
    "cost": 4,
    "attack": 4,
    "health": 4,
    "description": "Battlecry: If you have at least 4 other minions, deal 4 damage.",
    "image": "/cards/121.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "122",
    "name": "Heiliger Zorn",
    "cost": 7,
    "attack": 6,
    "health": 6,
    "description": "[x]Taunt\nDeathrattle: If you're holding\na Dragon, deal 3 damage\nto all minions.",
    "image": "/cards/122.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "123",
    "name": "Seelenstrudel",
    "cost": 6,
    "attack": 3,
    "health": 9,
    "description": "Whenever your hero takes damage, this minion takes it instead.",
    "image": "/cards/123.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "124",
    "name": "Waldläuferin (Variante)",
    "cost": 9,
    "attack": 10,
    "health": 10,
    "description": "Charge\nCan't attack heroes.",
    "image": "/cards/124.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "125",
    "name": "Giftige Dagger",
    "cost": 5,
    "attack": 4,
    "health": 5,
    "description": "Inspire: Add a random spell to your hand.",
    "image": "/cards/125.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "126",
    "name": "Stille",
    "cost": 6,
    "attack": 7,
    "health": 4,
    "description": "Deathrattle: Reveal a minion in each deck. If yours costs more, return this to your hand.",
    "image": "/cards/126.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "127",
    "name": "Naturgewalt",
    "cost": 3,
    "attack": 3,
    "health": 4,
    "description": "Whenever you target this minion with a spell, gain Divine Shield.",
    "image": "/cards/127.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "128",
    "name": "Heiliges Urteil",
    "cost": 6,
    "attack": 6,
    "health": 7,
    "description": "When you draw this, deal 1 damage to your minions.",
    "image": "/cards/128.jpg",
    "class": "Klingenmeister",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "129",
    "name": "Donnerlanze",
    "cost": 3,
    "attack": 3,
    "health": 4,
    "description": "Whenever you target this minion with a spell, deal 3 damage to a random enemy.",
    "image": "/cards/129.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "130",
    "name": "Nachtklaue",
    "cost": 6,
    "attack": 6,
    "health": 3,
    "description": "Battlecry: Replace your starting Hero Power with a better one.",
    "image": "/cards/130.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "131",
    "name": "Lichtaura",
    "cost": 1,
    "attack": 1,
    "health": 2,
    "description": "Battlecry: Reveal a minion in each deck. If yours costs more, gain +1/+1.",
    "image": "/cards/131.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "132",
    "name": "Seelenfeuer",
    "cost": 1,
    "attack": 1,
    "health": 1,
    "description": "Magnetic\nRush",
    "image": "/cards/132.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "133",
    "name": "Mondbär",
    "cost": 3,
    "attack": 1,
    "health": 5,
    "description": "Magnetic\nTaunt",
    "image": "/cards/133.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "134",
    "name": "Lichtpfeil",
    "cost": 1,
    "attack": 0,
    "health": 2,
    "description": "[x]Deathrattle: Deal 2 damage\nto the enemy hero.",
    "image": "/cards/134.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "135",
    "name": "Späher der Wälder",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Deal $2 damage. Summon a 0/2 Goblin Bomb.",
    "image": "/cards/135.jpg",
    "class": "Waldhüter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "136",
    "name": "Finsterer Fluch",
    "cost": 7,
    "attack": 5,
    "health": 5,
    "description": "Battlecry: Summon four 0/2 Goblin Bombs.",
    "image": "/cards/136.jpg",
    "class": "Waldhüter",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "137",
    "name": "Schmetterer",
    "cost": 2,
    "attack": 2,
    "health": 2,
    "description": "Magnetic\nPoisonous",
    "image": "/cards/137.jpg",
    "class": "Waldhüter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "138",
    "name": "Blutrausch",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "[x]Battlecry: Give a friendly\nMech +1/+1. If it has\nDeathrattle, trigger it.",
    "image": "/cards/138.jpg",
    "class": "Waldhüter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "139",
    "name": "Echoschatten",
    "cost": 5,
    "attack": 3,
    "health": 6,
    "description": "Your Deathrattles trigger twice.",
    "image": "/cards/139.jpg",
    "class": "Waldhüter",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "140",
    "name": "Manabrunnensucher",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Each player equips a 2/3 Weapon and\ngains 6 Armor.",
    "image": "/cards/140.jpg",
    "class": "Klingenmeister",
    "rarity": "common"
  },
  {
    "id": "141",
    "name": "Waldstachel",
    "cost": 5,
    "attack": 2,
    "health": 6,
    "description": "Taunt\nLifesteal",
    "image": "/cards/141.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "142",
    "name": "Runenwächter (Variante)",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Each player gains 2 Mana Crystals.",
    "image": "/cards/142.jpg",
    "class": "Naturrufer",
    "rarity": "common"
  },
  {
    "id": "143",
    "name": "Lichtschwinge",
    "cost": 1,
    "attack": 1,
    "health": 3,
    "description": "Whenever this minion takes damage, gain 2 Armor.",
    "image": "/cards/143.jpg",
    "class": "Klingenmeister",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "144",
    "name": "Felswächter",
    "cost": 6,
    "attack": 2,
    "health": 2,
    "description": "Deathrattle: Summon a 7/7 Mechanical Dragon.",
    "image": "/cards/144.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "145",
    "name": "Gedankendieb",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Give a minion Rush. Draw a card.",
    "image": "/cards/145.jpg",
    "class": "Klingenmeister",
    "rarity": "common"
  },
  {
    "id": "146",
    "name": "Tiefenwoge",
    "cost": 9,
    "attack": 0,
    "health": 0,
    "description": "Summon 3 random minions from your hand. Give them Rush.",
    "image": "/cards/146.jpg",
    "class": "Klingenmeister",
    "rarity": "legendary"
  },
  {
    "id": "147",
    "name": "Schattengabe",
    "cost": 1,
    "attack": 1,
    "health": 1,
    "description": "Battlecry: Give a friendly Mech +1/+1.",
    "image": "/cards/147.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "148",
    "name": "Tarnassischer Greif",
    "cost": 2,
    "attack": 2,
    "health": 2,
    "description": "Battlecry: Give your weapon +1 Attack.",
    "image": "/cards/148.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "149",
    "name": "Elementarfunke",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Add 2 random Deathrattle cards to your hand.",
    "image": "/cards/149.jpg",
    "class": "Klingenläufer",
    "rarity": "common"
  },
  {
    "id": "150",
    "name": "Klingentänzer",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "Shuffle 10 cards from your opponent's class into your deck. They cost (1).",
    "image": "/cards/150.jpg",
    "class": "Klingenläufer",
    "rarity": "epic"
  },
  {
    "id": "151",
    "name": "Totemrufer",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Draw a card. Copy it if you played an Elemental last turn.",
    "image": "/cards/151.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common"
  },
  {
    "id": "152",
    "name": "Seelenfänger",
    "cost": 2,
    "attack": 2,
    "health": 4,
    "description": "Can only attack if you cast a spell this turn.",
    "image": "/cards/152.jpg",
    "class": "neutral",
    "rarity": "rare"
  },
  {
    "id": "153",
    "name": "Wurzelgebunden",
    "cost": 6,
    "attack": 0,
    "health": 0,
    "description": "Summon a copy of a random minion from your hand.",
    "image": "/cards/153.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare"
  },
  {
    "id": "154",
    "name": "Heilige Woge",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Add 2 random minions to your hand.",
    "image": "/cards/154.jpg",
    "class": "Elementarwirker",
    "rarity": "rare"
  },
  {
    "id": "155",
    "name": "Splittersturm",
    "cost": 6,
    "attack": 5,
    "health": 1,
    "description": "Rush\nDeathrattle: Add two\n1/1 Sparks with Rush to your hand.",
    "image": "/cards/155.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "156",
    "name": "Nachtjägerin",
    "cost": 3,
    "attack": 2,
    "health": 4,
    "description": "After you play the\nright-most card in your hand, draw a card.",
    "image": "/cards/156.jpg",
    "class": "Elementarwirker",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "157",
    "name": "Stahlpanzer",
    "cost": 5,
    "attack": 3,
    "health": 4,
    "description": "Battlecry: Deal 5 damage randomly split among all minions except Mechs.",
    "image": "/cards/157.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "158",
    "name": "Traumfänger",
    "cost": 6,
    "attack": 4,
    "health": 4,
    "description": "[x]Magnetic\nAt the end of your turn,\ndeal 1 damage to all\nother characters.",
    "image": "/cards/158.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "159",
    "name": "Kettenschild",
    "cost": 3,
    "attack": 3,
    "health": 4,
    "description": "Battlecry: If you have 10 Mana Crystals, restore #10 Health to your hero.",
    "image": "/cards/159.jpg",
    "class": "Schattenwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "160",
    "name": "Blitzzunge",
    "cost": 6,
    "attack": 2,
    "health": 5,
    "description": "[x]Whenever this minion\ntakes damage, summon a\n2/3 Mech with Taunt.",
    "image": "/cards/160.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "161",
    "name": "Dorndiener",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "[x]Give a minion +2/+2.\nAdd 'More Arms!' to your\nhand that gives +2/+2.",
    "image": "/cards/161.jpg",
    "class": "Schattenwirker",
    "rarity": "rare"
  },
  {
    "id": "162",
    "name": "Dunkelpriesterin",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Deal $4 damage to a minion and your hero.",
    "image": "/cards/162.jpg",
    "class": "Seelenmeister",
    "rarity": "common"
  },
  {
    "id": "163",
    "name": "Wetterkontrolle",
    "cost": 3,
    "attack": 2,
    "health": 2,
    "description": "Battlecry: Summon a copy of this minion.",
    "image": "/cards/163.jpg",
    "class": "Seelenmeister",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "164",
    "name": "Splitterregen (Variante)",
    "cost": 3,
    "attack": 1,
    "health": 5,
    "description": "Battlecry: Gain +1 Attack for each damage your hero has taken this turn.",
    "image": "/cards/164.jpg",
    "class": "Seelenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "165",
    "name": "Dämonischer Lehrling",
    "cost": 5,
    "attack": 0,
    "health": 0,
    "description": "Set the Attack and Health of all minions\nto 1.",
    "image": "/cards/165.jpg",
    "class": "Lichtwächter",
    "rarity": "rare"
  },
  {
    "id": "166",
    "name": "Magmabinder",
    "cost": 2,
    "attack": 1,
    "health": 2,
    "description": "Divine Shield, Lifesteal\nYour healing is doubled.",
    "image": "/cards/166.jpg",
    "class": "Lichtwächter",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "167",
    "name": "Frostklaue",
    "cost": 7,
    "attack": 3,
    "health": 8,
    "description": "Magnetic\nCan't be targeted by spells or Hero Powers.",
    "image": "/cards/167.jpg",
    "class": "Klingenmeister",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "168",
    "name": "Siegelbrecherin",
    "cost": 7,
    "attack": 0,
    "health": 30,
    "description": "Battlecry: For the rest of the game, your Mechs have Rush.",
    "image": "/cards/168.jpg",
    "class": "Klingenmeister",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "169",
    "name": "Vollstrecker der Leere",
    "cost": 5,
    "attack": 0,
    "health": 0,
    "description": "Draw the rest of\nyour deck.",
    "image": "/cards/169.jpg",
    "class": "Klingenläufer",
    "rarity": "legendary"
  },
  {
    "id": "170",
    "name": "Sturmschlag",
    "cost": 5,
    "attack": 4,
    "health": 2,
    "description": "[x]Battlecry: Discover a\nDeathrattle minion. Also\ngain its Deathrattle.",
    "image": "/cards/170.jpg",
    "class": "Klingenläufer",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "171",
    "name": "Weg der Schatten",
    "cost": 7,
    "attack": 0,
    "health": 0,
    "description": "Transform your minions into random Legendary minions.",
    "image": "/cards/171.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "legendary"
  },
  {
    "id": "172",
    "name": "Heiliger Ruf",
    "cost": 0,
    "attack": 0,
    "health": 0,
    "description": "Deal $1 damage to all minions. Overload: (2)",
    "image": "/cards/172.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "173",
    "name": "Flammengeist",
    "cost": 3,
    "attack": 2,
    "health": 2,
    "description": "Magnetic\nDeathrattle: Destroy a random enemy minion.",
    "image": "/cards/173.jpg",
    "class": "Waldhüter",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "174",
    "name": "Schlangenfalle",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "[x]Summon two random\n$2-Cost minions (improved\nby Spell Damage).",
    "image": "/cards/174.jpg",
    "class": "Elementarwirker",
    "rarity": "epic"
  },
  {
    "id": "175",
    "name": "Astralwandlerin",
    "cost": 7,
    "attack": 5,
    "health": 5,
    "description": "[x]Battlecry: Summon a\nrandom minion with Cost\nequal to your hand size.",
    "image": "/cards/175.jpg",
    "class": "Elementarwirker",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "176",
    "name": "Seelenritt",
    "cost": 7,
    "attack": 0,
    "health": 0,
    "description": "Change the Cost of minions in your\ndeck to (1).",
    "image": "/cards/176.jpg",
    "class": "Elementarwirker",
    "rarity": "legendary"
  },
  {
    "id": "177",
    "name": "Totemgolem",
    "cost": 6,
    "attack": 5,
    "health": 5,
    "description": "Deathrattle: If you've cast any spells on this minion, resummon it.",
    "image": "/cards/177.jpg",
    "class": "Schattenwirker",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "178",
    "name": "Naturgewalt (Variante)",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Give the\nleft-most minion in your hand +2/+2.",
    "image": "/cards/178.jpg",
    "class": "Seelenmeister",
    "rarity": "rare"
  },
  {
    "id": "179",
    "name": "Kristallformung",
    "cost": 4,
    "attack": 4,
    "health": 3,
    "description": "Deathrattle: Summon a random minion from\nyour hand that costs (2) or less.",
    "image": "/cards/179.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "180",
    "name": "Klingenwirbel",
    "cost": 5,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Summon two 1/2 Mechs with Taunt and Divine Shield.",
    "image": "/cards/180.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "181",
    "name": "Manaschub",
    "cost": 5,
    "attack": 3,
    "health": 3,
    "description": "After your opponent plays a minion, summon a 1/1 copy of it.",
    "image": "/cards/181.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "182",
    "name": "Wellenformer (Variante)",
    "cost": 2,
    "attack": 1,
    "health": 1,
    "description": "[x]Battlecry: Gain +2/+2 for\neach other Pogo-Hopper\nyou played this game.",
    "image": "/cards/182.jpg",
    "class": "Klingenläufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "183",
    "name": "Gedankenklaue",
    "cost": 3,
    "attack": 3,
    "health": 0,
    "description": "Deathrattle: Trigger the Deathrattle of a random friendly minion.",
    "image": "/cards/183.jpg",
    "class": "Klingenläufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "184",
    "name": "Lichtsegen",
    "cost": 2,
    "attack": 3,
    "health": 2,
    "description": "Battlecry: Shuffle 3 copies of a friendly minion into your deck.",
    "image": "/cards/184.jpg",
    "class": "Klingenläufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "185",
    "name": "Feuerkrähe",
    "cost": 4,
    "attack": 3,
    "health": 4,
    "description": "Battlecry: Draw a spell from your deck that costs (5) or more.",
    "image": "/cards/185.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "186",
    "name": "Seelensog",
    "cost": 4,
    "attack": 2,
    "health": 6,
    "description": "[x]Taunt\nBattlecry: If you have\n10 Mana Crystals,\ngain +10 Attack.",
    "image": "/cards/186.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "187",
    "name": "Runenrüstung",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "[x]Discover a Mech. If you\nhave 10 Mana Crystals,\nkeep all 3 cards.",
    "image": "/cards/187.jpg",
    "class": "Klingenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "188",
    "name": "Knochenspuk",
    "cost": 3,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Deal 2 damage.",
    "image": "/cards/188.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "189",
    "name": "Felsformer",
    "cost": 2,
    "attack": 1,
    "health": 5,
    "description": "",
    "image": "/cards/189.jpg",
    "class": "neutral",
    "rarity": "common"
  },
  {
    "id": "190",
    "name": "Klingenregen",
    "cost": 4,
    "attack": 3,
    "health": 1,
    "description": "Magnetic\nDeathrattle: Summon three 1/1 Microbots.",
    "image": "/cards/190.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "191",
    "name": "Doppeltes Spiel",
    "cost": 4,
    "attack": 4,
    "health": 3,
    "description": "Deathrattle: Add a random Legendary minion to your hand.",
    "image": "/cards/191.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "192",
    "name": "Waldläuferin (Variante 2)",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Discover a Secret.",
    "image": "/cards/192.jpg",
    "class": "Waldhüter",
    "rarity": "common"
  },
  {
    "id": "193",
    "name": "Blutrausch (Variante)",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "Draw a 7, 8, 9, and\n10-Cost minion\n from your deck.",
    "image": "/cards/193.jpg",
    "class": "Naturrufer",
    "rarity": "epic"
  },
  {
    "id": "194",
    "name": "Klingenakrobat",
    "cost": 5,
    "attack": 1,
    "health": 0,
    "description": "[x]After you attack a minion,\nforce it to attack one\nof its neighbors.",
    "image": "/cards/194.jpg",
    "class": "Klingenmeister",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "195",
    "name": "Sturmrufer",
    "cost": 4,
    "attack": 3,
    "health": 5,
    "description": "[x]After you play a card with\nOverload, summon two\n1/1 Sparks with Rush.",
    "image": "/cards/195.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "196",
    "name": "Schattengeister",
    "cost": 3,
    "attack": 3,
    "health": 3,
    "description": "Battlecry: Your next spell this turn casts twice.",
    "image": "/cards/196.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "197",
    "name": "Seelenbrand",
    "cost": 3,
    "attack": 3,
    "health": 1,
    "description": "[x]Battlecry: Gain +1 Health\nfor each spell in your hand.",
    "image": "/cards/197.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "198",
    "name": "Stahlbiss",
    "cost": 2,
    "attack": 1,
    "health": 2,
    "description": "Stealth\nDivine Shield",
    "image": "/cards/198.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "199",
    "name": "Segen der Flamme",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "Battlecry: If you control a Treant, Discover a spell.",
    "image": "/cards/199.jpg",
    "class": "Naturrufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "200",
    "name": "Mondlichtsegen",
    "cost": 3,
    "attack": 0,
    "health": 0,
    "description": "Summon two 2/2 Treants.",
    "image": "/cards/200.jpg",
    "class": "Naturrufer",
    "rarity": "common"
  },
  {
    "id": "201",
    "name": "Wilde Pranke",
    "cost": 6,
    "attack": 3,
    "health": 4,
    "description": "[x]Choose One - Give your\nother minions +1/+1;\nor Summon two\n2/2 Treants.",
    "image": "/cards/201.jpg",
    "class": "Naturrufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "202",
    "name": "Manablitz",
    "cost": 7,
    "attack": 4,
    "health": 4,
    "description": "At the end of your turn, reduce the Cost of a random minion in your hand by (7).",
    "image": "/cards/202.jpg",
    "class": "Naturrufer",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "203",
    "name": "Blutschwur",
    "cost": 10,
    "attack": 10,
    "health": 10,
    "description": "[x]Deathrattle: If you have no\ncards in your deck, hand,\nand battlefield, destroy\nthe enemy hero.",
    "image": "/cards/203.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "204",
    "name": "Eiserner Schildträger",
    "cost": 8,
    "attack": 0,
    "health": 0,
    "description": "[x]Summon 3 minions from\nyour deck. They attack\nenemy minions, then die.",
    "image": "/cards/204.jpg",
    "class": "Waldhüter",
    "rarity": "legendary"
  },
  {
    "id": "205",
    "name": "Zwillingsschläge",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Summon a 0/2 Goblin Bomb.",
    "image": "/cards/205.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "206",
    "name": "Wurzelwache",
    "cost": 8,
    "attack": 5,
    "health": 5,
    "description": "Deathrattle: Swap this with a minion from your deck.",
    "image": "/cards/206.jpg",
    "class": "Seelenmeister",
    "rarity": "legendary",
    "mechanics": []
  },
  {
    "id": "207",
    "name": "Sturmkrähe",
    "cost": 4,
    "attack": 3,
    "health": 4,
    "description": "While in your hand, this is a 3/4 copy of the last minion you played.",
    "image": "/cards/207.jpg",
    "class": "Naturrufer",
    "rarity": "legendary"
  },
  {
    "id": "208",
    "name": "Schattenkuss",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Discover a copy of a minion in your opponent's deck.",
    "image": "/cards/208.jpg",
    "class": "Schattenwirker",
    "rarity": "common"
  },
  {
    "id": "209",
    "name": "Lichtschildmagierin",
    "cost": 4,
    "attack": 0,
    "health": 0,
    "description": "Draw a minion and a spell from your deck. Swap their Costs.",
    "image": "/cards/209.jpg",
    "class": "Lichtwächter",
    "rarity": "epic"
  },
  {
    "id": "210",
    "name": "Flammenzunge",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Give a friendly minion +3/+3 and Rush. It dies at end of turn.",
    "image": "/cards/210.jpg",
    "class": "Waldhüter",
    "rarity": "epic"
  },
  {
    "id": "211",
    "name": "Klingenrüstung",
    "cost": 2,
    "attack": 0,
    "health": 0,
    "description": "Give your minions \"Deathrattle: Add a random Mech to your hand.\"",
    "image": "/cards/211.jpg",
    "class": "Waldhüter",
    "rarity": "rare"
  },
  {
    "id": "212",
    "name": "Manaschild",
    "cost": 2,
    "attack": 2,
    "health": 2,
    "description": "Deathrattle: Give all Demons in your hand +1/+1.",
    "image": "/cards/212.jpg",
    "class": "Seelenmeister",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "213",
    "name": "Seelenfeuer (Variante)",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Whenever a minion dies this turn, gain 1 Mana Crystal this turn only.",
    "image": "/cards/213.jpg",
    "class": "Naturrufer",
    "rarity": "legendary"
  },
  {
    "id": "214",
    "name": "Blitzgeschmiedeter",
    "cost": 1,
    "attack": 1,
    "health": 1,
    "description": "Deathrattle: Summon a 1/1 Jo-E Bot.",
    "image": "/cards/214.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "215",
    "name": "Waldstreuner",
    "cost": 1,
    "attack": 1,
    "health": 3,
    "description": "[x]Battlecry: Deal 5 damage\nto your hero. Gain 5 Armor.",
    "image": "/cards/215.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "216",
    "name": "Runenbann",
    "cost": 6,
    "attack": 5,
    "health": 12,
    "description": "Taunt\nBattlecry: Deal 6 damage to this minion.",
    "image": "/cards/216.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "217",
    "name": "Wellenreiter",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Summon two 1/1 Sparks with Rush. Overload: (1)",
    "image": "/cards/217.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "218",
    "name": "Feuerling",
    "cost": 1,
    "attack": 0,
    "health": 0,
    "description": "Deal $1 damage to a minion and the minions next to it.",
    "image": "/cards/218.jpg",
    "class": "Elementarwirker",
    "rarity": "common"
  },
  {
    "id": "219",
    "name": "Wächter des Waldes",
    "cost": 8,
    "attack": 4,
    "health": 4,
    "description": "Battlecry: Summon a copy of each adjacent minion.",
    "image": "/cards/219.jpg",
    "class": "Naturrufer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "220",
    "name": "Flammenkralle",
    "cost": 5,
    "attack": 0,
    "health": 0,
    "description": "Trigger a friendly minion's Deathrattle twice.",
    "image": "/cards/220.jpg",
    "class": "Klingenläufer",
    "rarity": "epic"
  },
  {
    "id": "221",
    "name": "Seelensplitter",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "Deathrattle: Draw a Deathrattle minion from your deck.",
    "image": "/cards/221.jpg",
    "class": "Schattenwirker",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "222",
    "name": "Blitzkralle",
    "cost": 5,
    "attack": 5,
    "health": 5,
    "description": "[x]Battlecry: Shuffle a Bomb\ninto your opponent's deck.\nWhen drawn, it explodes\nfor 5 damage.",
    "image": "/cards/222.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "223",
    "name": "Waldgeistbiss",
    "cost": 0,
    "attack": 0,
    "health": 0,
    "description": "Swap a minion's Attack and Health.",
    "image": "/cards/223.jpg",
    "class": "Schattenwirker",
    "rarity": "common"
  },
  {
    "id": "224",
    "name": "Rüstungsschlag",
    "cost": 6,
    "attack": 0,
    "health": 0,
    "description": "Summon copies of all Demons you control.",
    "image": "/cards/224.jpg",
    "class": "Seelenmeister",
    "rarity": "epic"
  },
  {
    "id": "225",
    "name": "Flammenregen",
    "cost": 10,
    "attack": 8,
    "health": 8,
    "description": "Rush. Costs (1) less for each friendly Treant that died this game.",
    "image": "/cards/225.jpg",
    "class": "Naturrufer",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "226",
    "name": "Dunkelberührung",
    "cost": 5,
    "attack": 0,
    "health": 0,
    "description": "Choose a friendly minion. Summon a 5/5 copy of it.",
    "image": "/cards/226.jpg",
    "class": "Schattenwirker",
    "rarity": "epic"
  },
  {
    "id": "227",
    "name": "Waldheiler",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Your next spell this turn has Spell Damage +2.",
    "image": "/cards/227.jpg",
    "class": "Elementarwirker",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "228",
    "name": "Ritualklinge",
    "cost": 4,
    "attack": 3,
    "health": 2,
    "description": "Battlecry: Summon two 0/2 Goblin Bombs.",
    "image": "/cards/228.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "229",
    "name": "Wutsturm",
    "cost": 2,
    "attack": 2,
    "health": 2,
    "description": "Battlecry: Add a random Elemental to your hand.",
    "image": "/cards/229.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "230",
    "name": "Windgeist",
    "cost": 9,
    "attack": 9,
    "health": 7,
    "description": "Divine Shield",
    "image": "/cards/230.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "231",
    "name": "Mondrufer",
    "cost": 3,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Summon two 1/1 Microbots.",
    "image": "/cards/231.jpg",
    "class": "neutral",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "232",
    "name": "Gedankensog",
    "cost": 5,
    "attack": 4,
    "health": 5,
    "description": "[x]Battlecry: If you have 10\nMana Crystals, summon\n 2 copies of this minion.",
    "image": "/cards/232.jpg",
    "class": "Seelenmeister",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "233",
    "name": "Elementarfunke (Variante)",
    "cost": 5,
    "attack": 0,
    "health": 5,
    "description": "Deathrattle: Summon an 8/8 Robosaur.",
    "image": "/cards/233.jpg",
    "class": "Lichtwächter",
    "rarity": "common",
    "mechanics": []
  },
  {
    "id": "234",
    "name": "Naturwächter",
    "cost": 2,
    "attack": 2,
    "health": 1,
    "description": "Battlecry: Add a \n1/1 Spark with Rush to your hand.",
    "image": "/cards/234.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "235",
    "name": "Klingenpirscher",
    "cost": 6,
    "attack": 3,
    "health": 4,
    "description": "Battlecry: Discover a spell that costs (5) or more.",
    "image": "/cards/235.jpg",
    "class": "neutral",
    "rarity": "rare",
    "mechanics": []
  },
  {
    "id": "236",
    "name": "Sturmzauber",
    "cost": 5,
    "attack": 3,
    "health": 3,
    "description": "Battlecry: Destroy a Mech.",
    "image": "/cards/236.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "237",
    "name": "Wellenformer (Variante 2)",
    "cost": 2,
    "attack": 2,
    "health": 3,
    "description": "[x]Battlecry: If you have 10\nMana Crystals, your spells\n have Lifesteal this turn.",
    "image": "/cards/237.jpg",
    "class": "Sturmbeschwörer",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "238",
    "name": "Klingenmagier",
    "cost": 5,
    "attack": 6,
    "health": 6,
    "description": "Battlecry: Deal 6 damage randomly split among other friendly minions.",
    "image": "/cards/238.jpg",
    "class": "neutral",
    "rarity": "epic",
    "mechanics": []
  },
  {
    "id": "239",
    "name": "Letzter Funken",
    "cost": 5,
    "attack": 3,
    "health": 2,
    "description": "Magnetic\nDivine Shield, Taunt, Lifesteal, Rush",
    "image": "/cards/239.jpg",
    "class": "neutral",
    "rarity": "legendary",
    "mechanics": []
  }
];
