
export type CardData = {
  id: string;
  name: string;
  cost: number;
  attack: number;
  health: number;
  description: string;
  image: string;
  class: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
  mechanics?: string[];
};

export const allCards: CardData[] = [
  {
    id: '001',
    name: 'Waldhauch',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Zieht eine Karte.',
    image: '/cards/001.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '002',
    name: 'Rindenhaut-Schützer',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Schild (Spott).',
    image: '/cards/002.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '003',
    name: 'Lebenswurzel',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Stellt 4 Leben wieder her.',
    image: '/cards/003.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['heal']
  },
  {
    id: '004',
    name: 'Zornklinge',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Ansturm.',
    image: '/cards/004.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '005',
    name: 'Magmaschlag',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 6 Schaden.',
    image: '/cards/005.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['damage']
  },
  {
    id: '006',
    name: 'Lichtnova',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen Feinden.',
    image: '/cards/006.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['aoe']
  },
  {
    id: '007',
    name: 'Schattengeist',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Beim Ausspielen: Gegner verliert 2 Leben.',
    image: '/cards/007.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['battlecry']
  },
  {
    id: '008',
    name: 'Windwandler',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Doppelschlag (Greift zweimal an).',
    image: '/cards/008.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '009',
    name: 'Klingenhexe',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Kampfschrei: Fügt einem Gegner 3 Schaden zu.',
    image: '/cards/009.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['battlecry']
  },
  {
    id: '010',
    name: 'Auge des Waldes',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Ziehe 2 Karten.',
    image: '/cards/010.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '011',
    name: 'Dämonenstoß',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden.',
    image: '/cards/011.jpg',
    class: 'Seelenmeister',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '012',
    name: 'Kristallheiler',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Heilt 3 Leben bei allen Verbündeten.',
    image: '/cards/012.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['aoe', 'heal']
  },
  {
    id: '013',
    name: 'Nebelkrieger',
    cost: 2,
    attack: 3,
    health: 1,
    description: 'Verborgensein.',
    image: '/cards/013.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '014',
    name: 'Runenwächter',
    cost: 5,
    attack: 4,
    health: 6,
    description: 'Schild.',
    image: '/cards/014.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '015',
    name: 'Flammenbote',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Zauberschaden +1.',
    image: '/cards/015.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '016',
    name: 'Todeshauch',
    cost: 4,
    attack: 2,
    health: 4,
    description: 'Todesröcheln: Verursacht 2 Schaden an allen Gegnern.',
    image: '/cards/016.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['deathrattle']
  },
  {
    id: '017',
    name: 'Seelenbrenner',
    cost: 5,
    attack: 5,
    health: 4,
    description: 'Beim Ausspielen: Ziehe eine Karte.',
    image: '/cards/017.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['battlecry', 'draw']
  },
  {
    id: '018',
    name: 'Donnerfaust',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Ansturm.',
    image: '/cards/018.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '019',
    name: 'Wachposten',
    cost: 2,
    attack: 1,
    health: 4,
    description: 'Schild.',
    image: '/cards/019.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '020',
    name: 'Lichtfunken',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Heilt 2 Leben.',
    image: '/cards/020.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['heal']
  }
    {
    id: '021',
    name: 'Seelensucher',
    cost: 3,
    attack: 2,
    health: 4,
    description: 'Todesröcheln: Ziehe eine Karte.',
    image: '/cards/021.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['deathrattle', 'draw']
  },
  {
    id: '022',
    name: 'Naturpfad',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Erhalte 2 Mana in diesem Zug.',
    image: '/cards/022.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['manaboost']
  },
  {
    id: '023',
    name: 'Stahlfalke',
    cost: 4,
    attack: 4,
    health: 3,
    description: 'Windzorn.',
    image: '/cards/023.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '024',
    name: 'Schattenflamme',
    cost: 5,
    attack: 0,
    health: 0,
    description: 'Opfere einen Diener. Verursacht dessen Angriff als Schaden an allen Gegnern.',
    image: '/cards/024.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['sacrifice', 'aoe']
  },
  {
    id: '025',
    name: 'Runenschlag',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden. Zauberschaden wird angerechnet.',
    image: '/cards/025.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['damage', 'spellpower']
  },
  {
    id: '026',
    name: 'Windgeheul',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Verleiht einem Diener +1 Angriff.',
    image: '/cards/026.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['battlecry', 'buff']
  },
  {
    id: '027',
    name: 'Splitterklinge',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Verborgensein.',
    image: '/cards/027.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '028',
    name: 'Glanzschild-Wächter',
    cost: 4,
    attack: 3,
    health: 5,
    description: 'Schild.',
    image: '/cards/028.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '029',
    name: 'Dunkelpriester',
    cost: 5,
    attack: 4,
    health: 4,
    description: 'Kampfschrei: Übernimmt die Kontrolle über einen feindlichen Diener mit 2 oder weniger Angriff.',
    image: '/cards/029.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'control']
  },
  {
    id: '030',
    name: 'Flammenschlag',
    cost: 7,
    attack: 0,
    health: 0,
    description: 'Verursacht 4 Schaden an allen gegnerischen Dienern.',
    image: '/cards/030.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '031',
    name: 'Pfadfinder',
    cost: 1,
    attack: 1,
    health: 1,
    description: 'Zieht eine Karte.',
    image: '/cards/031.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['draw']
  },
  {
    id: '032',
    name: 'Energiedieb',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Beim Ausspielen: Stehle 1 Mana-Kristall in diesem Zug.',
    image: '/cards/032.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'manasteal']
  },
  {
    id: '033',
    name: 'Wurzelkoloss',
    cost: 6,
    attack: 5,
    health: 6,
    description: 'Schild.',
    image: '/cards/033.jpg',
    class: 'Naturrufer',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '034',
    name: 'Dämonisches Feuer',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Fügt einem Diener 2 Schaden zu. Wenn es ein eigener Dämon ist, erhält er stattdessen +2/+2.',
    image: '/cards/034.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['damage', 'conditionalbuff']
  },
  {
    id: '035',
    name: 'Schildsänger',
    cost: 3,
    attack: 2,
    health: 5,
    description: 'Schild.',
    image: '/cards/035.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '036',
    name: 'Donnerzorn',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen Feinden.',
    image: '/cards/036.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '037',
    name: 'Dämmerungsmagier',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Zauberschaden +1.',
    image: '/cards/037.jpg',
    class: 'Elementarwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '038',
    name: 'Waldläuferin',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Kampfschrei: Zieht 1 Karte.',
    image: '/cards/038.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['battlecry', 'draw']
  },
  {
    id: '039',
    name: 'Kettenblitz',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden an einem Ziel und 1 Schaden an benachbarten Zielen.',
    image: '/cards/039.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '040',
    name: 'Schattenläufer',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/040.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  }
  {
    id: '041',
    name: 'Kristallformer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Erhalte einen zusätzlichen Mana-Kristall in diesem Zug.',
    image: '/cards/041.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['battlecry', 'manaboost']
  },
  {
    id: '042',
    name: 'Echoschlitzer',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Windzorn.',
    image: '/cards/042.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['windfury']
  },
  {
    id: '043',
    name: 'Lebensweber',
    cost: 4,
    attack: 2,
    health: 6,
    description: 'Am Ende deines Zuges: Heile deinen Helden um 2 Leben.',
    image: '/cards/043.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['healing', 'endofturn']
  },
  {
    id: '044',
    name: 'Sturmkralle',
    cost: 3,
    attack: 3,
    health: 2,
    description: 'Kampfschrei: Fügt einem feindlichen Diener 2 Schaden zu.',
    image: '/cards/044.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['battlecry', 'damage']
  },
  {
    id: '045',
    name: 'Dornenwächter',
    cost: 5,
    attack: 4,
    health: 6,
    description: 'Schild.',
    image: '/cards/045.jpg',
    class: 'Naturrufer',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '046',
    name: 'Dämonenzorn',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an allen nicht-dämonischen Dienern.',
    image: '/cards/046.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['aoe', 'conditional']
  },
  {
    id: '047',
    name: 'Frostklinge',
    cost: 2,
    attack: 3,
    health: 1,
    description: 'Einfrieren jedes Dieners, dem dieser Diener Schaden zufügt.',
    image: '/cards/047.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['freeze', 'damage']
  },
  {
    id: '048',
    name: 'Runenpriester',
    cost: 3,
    attack: 3,
    health: 4,
    description: 'Zauberschaden +1.',
    image: '/cards/048.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['spellpower']
  },
  {
    id: '049',
    name: 'Wurzelranke',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Kampfschrei: Heilt 2 Leben.',
    image: '/cards/049.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['battlecry', 'healing']
  },
  {
    id: '050',
    name: 'Blutpakt',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Ziehe 2 Karten und erhalte 3 Schaden.',
    image: '/cards/050.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['draw', 'selfdamage']
  },
  {
    id: '051',
    name: 'Lichtformer',
    cost: 2,
    attack: 2,
    health: 2,
    description: 'Kampfschrei: Verleiht einem anderen Diener +1/+1.',
    image: '/cards/051.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['battlecry', 'buff']
  },
  {
    id: '052',
    name: 'Tiefenschleicher',
    cost: 3,
    attack: 4,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/052.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '053',
    name: 'Dunkelklaue',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Zufälliger Feind erhält 3 Schaden beim Ausspielen.',
    image: '/cards/053.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'randomdamage']
  },
  {
    id: '054',
    name: 'Kettenheiler',
    cost: 4,
    attack: 2,
    health: 6,
    description: 'Kampfschrei: Heilt 3 Leben bei allen verbündeten Charakteren.',
    image: '/cards/054.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['battlecry', 'aoehealing']
  },
  {
    id: '055',
    name: 'Energiefokus',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Ziehe eine Karte. Zauberschaden +1 für diesen Zug.',
    image: '/cards/055.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['draw', 'temporaryspellpower']
  },
  {
    id: '056',
    name: 'Wellenformer',
    cost: 4,
    attack: 2,
    health: 5,
    description: 'Windzorn.',
    image: '/cards/056.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['windfury']
  },
  {
    id: '057',
    name: 'Funkenschlag',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden. Wenn es einen Diener tötet, ziehe eine Karte.',
    image: '/cards/057.jpg',
    class: 'Waldhüter',
    rarity: 'rare',
    mechanics: ['damage', 'draw']
  },
  {
    id: '058',
    name: 'Geisterrausch',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Fügt allen Dienern 1 Schaden zu. Für jeden getöteten: Ziehe eine Karte.',
    image: '/cards/058.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'draw']
  },
  {
    id: '059',
    name: 'Höllenfeuer',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden an allen Charakteren.',
    image: '/cards/059.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '060',
    name: 'Astralkugel',
    cost: 6,
    attack: 0,
    health: 0,
    description: 'Ziehe 3 Karten.',
    image: '/cards/060.jpg',
    class: 'Elementarwirker',
    rarity: 'epic',
    mechanics: ['draw']
  }
  {
    id: '061',
    name: 'Schattenseherin',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Zauber kosten (1) weniger.',
    image: '/cards/061.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['spellcostreduction']
  },
  {
    id: '062',
    name: 'Kristallhieb',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Verursacht 3 Schaden.',
    image: '/cards/062.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['damage']
  },
  {
    id: '063',
    name: 'Urwächter',
    cost: 6,
    attack: 6,
    health: 5,
    description: 'Schild.',
    image: '/cards/063.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['taunt']
  },
  {
    id: '064',
    name: 'Lichturteil',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Zerstört einen feindlichen Diener mit 3 oder weniger Angriff.',
    image: '/cards/064.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['destroy', 'conditional']
  },
  {
    id: '065',
    name: 'Splitterklinge',
    cost: 3,
    attack: 4,
    health: 1,
    description: 'Durchbohren. Verursacht doppelten Schaden an Schilden.',
    image: '/cards/065.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['pierce', 'antitaunt']
  },
  {
    id: '066',
    name: 'Blutgesang',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Heilt 4 Leben.',
    image: '/cards/066.jpg',
    class: 'Schattenwirker',
    rarity: 'common',
    mechanics: ['healing']
  },
  {
    id: '067',
    name: 'Donnerhau',
    cost: 4,
    attack: 5,
    health: 4,
    description: 'Kampfschrei: Füge einem Gegner 2 Schaden zu.',
    image: '/cards/067.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'common',
    mechanics: ['battlecry', 'damage']
  },
  {
    id: '068',
    name: 'Waldschleicher',
    cost: 1,
    attack: 1,
    health: 2,
    description: 'Verborgensein.',
    image: '/cards/068.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['stealth']
  },
  {
    id: '069',
    name: 'Manaspule',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Erhalte 1 Mana nur für diesen Zug.',
    image: '/cards/069.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['manaboost', 'temporary']
  },
  {
    id: '070',
    name: 'Knochengardist',
    cost: 4,
    attack: 3,
    health: 6,
    description: 'Schild.',
    image: '/cards/070.jpg',
    class: 'Klingenmeister',
    rarity: 'epic',
    mechanics: ['taunt']
  },
  {
    id: '071',
    name: 'Wurzelnetz',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Einen Gegner festhalten (kann nächsten Zug nicht angreifen).',
    image: '/cards/071.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['disable', 'root']
  },
  {
    id: '072',
    name: 'Ritual des Schmerzes',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Füge ALLEN Dienern 2 Schaden zu.',
    image: '/cards/072.jpg',
    class: 'Seelenmeister',
    rarity: 'epic',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '073',
    name: 'Funkenpriesterin',
    cost: 2,
    attack: 2,
    health: 3,
    description: 'Zauberschaden +1.',
    image: '/cards/073.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '074',
    name: 'Klingentänzerin',
    cost: 3,
    attack: 3,
    health: 3,
    description: 'Eile.',
    image: '/cards/074.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['rush']
  },
  {
    id: '075',
    name: 'Dunkelmeditation',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ziehe 2 Karten.',
    image: '/cards/075.jpg',
    class: 'Schattenwirker',
    rarity: 'rare',
    mechanics: ['draw']
  },
  {
    id: '076',
    name: 'Splitterregen',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Fügt allen feindlichen Dienern 2 Schaden zu.',
    image: '/cards/076.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['aoe', 'damage']
  },
  {
    id: '077',
    name: 'Heilende Aura',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Heilt 3 Leben bei allen verbündeten Charakteren.',
    image: '/cards/077.jpg',
    class: 'Lichtwächter',
    rarity: 'epic',
    mechanics: ['aoehealing']
  },
  {
    id: '078',
    name: 'Widerstandsschrei',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verleiht deinen Dienern +0/+2.',
    image: '/cards/078.jpg',
    class: 'Klingenmeister',
    rarity: 'common',
    mechanics: ['buff']
  },
  {
    id: '079',
    name: 'Wacholderbär',
    cost: 5,
    attack: 5,
    health: 6,
    description: 'Schild.',
    image: '/cards/079.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['taunt']
  },
  {
    id: '080',
    name: 'Blitzritual',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verursacht 2 Schaden an einem Ziel. Überladung: 1',
    image: '/cards/080.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['damage', 'overload']
  }
  {
    id: '081',
    name: 'Zornkrähe',
    cost: 2,
    attack: 2,
    health: 1,
    description: 'Windzorn.',
    image: '/cards/081.jpg',
    class: 'Waldhüter',
    rarity: 'common',
    mechanics: ['windfury']
  },
  {
    id: '082',
    name: 'Lichtblitz',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Verursacht 1 Schaden. Zauberschaden wirkt zusätzlich.',
    image: '/cards/082.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['damage', 'spellpower']
  },
  {
    id: '083',
    name: 'Schattenformer',
    cost: 5,
    attack: 5,
    health: 5,
    description: 'Kampfschrei: Verdoppelt den nächsten Zauber.',
    image: '/cards/083.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['battlecry', 'spellboost']
  },
  {
    id: '084',
    name: 'Runenstecher',
    cost: 3,
    attack: 2,
    health: 4,
    description: 'Zauberschaden +1.',
    image: '/cards/084.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['spellpower']
  },
  {
    id: '085',
    name: 'Wurzelspeer',
    cost: 4,
    attack: 4,
    health: 4,
    description: 'Kampfschrei: Gibt Schild.',
    image: '/cards/085.jpg',
    class: 'Naturrufer',
    rarity: 'rare',
    mechanics: ['battlecry', 'taunt']
  },
  {
    id: '086',
    name: 'Klingenfurie',
    cost: 2,
    attack: 3,
    health: 2,
    description: 'Eile.',
    image: '/cards/086.jpg',
    class: 'Klingenläufer',
    rarity: 'common',
    mechanics: ['rush']
  },
  {
    id: '087',
    name: 'Geisterklaue',
    cost: 3,
    attack: 4,
    health: 3,
    description: 'Unsichtbar.',
    image: '/cards/087.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['stealth']
  },
  {
    id: '088',
    name: 'Aegis-Wächter',
    cost: 5,
    attack: 2,
    health: 7,
    description: 'Schild. Kann nicht betäubt werden.',
    image: '/cards/088.jpg',
    class: 'Klingenmeister',
    rarity: 'epic',
    mechanics: ['taunt', 'immunestun']
  },
  {
    id: '089',
    name: 'Schleiermagie',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Deine Diener erhalten Verborgensein für 1 Zug.',
    image: '/cards/089.jpg',
    class: 'Elementarwirker',
    rarity: 'rare',
    mechanics: ['stealth', 'temporary']
  },
  {
    id: '090',
    name: 'Lebensfunke',
    cost: 1,
    attack: 0,
    health: 0,
    description: 'Heilt 2 Leben und zieht eine Karte.',
    image: '/cards/090.jpg',
    class: 'Lichtwächter',
    rarity: 'common',
    mechanics: ['healing', 'draw']
  },
  {
    id: '091',
    name: 'Kriegsbär',
    cost: 6,
    attack: 5,
    health: 6,
    description: 'Schild. Ansturm.',
    image: '/cards/091.jpg',
    class: 'Waldhüter',
    rarity: 'epic',
    mechanics: ['taunt', 'rush']
  },
  {
    id: '092',
    name: 'Magmaschleuder',
    cost: 4,
    attack: 4,
    health: 3,
    description: 'Zauberschaden +2.',
    image: '/cards/092.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'epic',
    mechanics: ['spellpower']
  },
  {
    id: '093',
    name: 'Knochenrüstung',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Dein Held erhält +5 Rüstung.',
    image: '/cards/093.jpg',
    class: 'Klingenmeister',
    rarity: 'rare',
    mechanics: ['armor']
  },
  {
    id: '094',
    name: 'Schattenschritt',
    cost: 0,
    attack: 0,
    health: 0,
    description: 'Bringe einen befreundeten Diener zurück auf deine Hand. Er kostet (2) weniger.',
    image: '/cards/094.jpg',
    class: 'Klingenläufer',
    rarity: 'epic',
    mechanics: ['bounce', 'costreduction']
  },
  {
    id: '095',
    name: 'Seelenopfer',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Zerstört einen deiner Diener und zieht 2 Karten.',
    image: '/cards/095.jpg',
    class: 'Seelenmeister',
    rarity: 'rare',
    mechanics: ['sacrifice', 'draw']
  },
  {
    id: '096',
    name: 'Natursegen',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Verleiht einem Diener +2/+2.',
    image: '/cards/096.jpg',
    class: 'Naturrufer',
    rarity: 'common',
    mechanics: ['buff']
  },
  {
    id: '097',
    name: 'Erleuchtung',
    cost: 2,
    attack: 0,
    health: 0,
    description: 'Ziehe eine Karte. Wenn es ein Zauber ist, kostet er (1) weniger.',
    image: '/cards/097.jpg',
    class: 'Lichtwächter',
    rarity: 'rare',
    mechanics: ['draw', 'conditional', 'costreduction']
  },
  {
    id: '098',
    name: 'Sturmbote',
    cost: 5,
    attack: 6,
    health: 5,
    description: 'Überladung: 1.',
    image: '/cards/098.jpg',
    class: 'Sturmbeschwörer',
    rarity: 'rare',
    mechanics: ['overload']
  },
  {
    id: '099',
    name: 'Finstere Flamme',
    cost: 4,
    attack: 0,
    health: 0,
    description: 'Verursacht 5 Schaden. Heile dich um den verursachten Schaden.',
    image: '/cards/099.jpg',
    class: 'Schattenwirker',
    rarity: 'epic',
    mechanics: ['damage', 'lifesteal']
  },
  {
    id: '100',
    name: 'Klingenruf',
    cost: 3,
    attack: 0,
    health: 0,
    description: 'Beschwört zwei 1/1-Klingenlinge mit Eile.',
    image: '/cards/100.jpg',
    class: 'Klingenläufer',
    rarity: 'rare',
    mechanics: ['summon', 'rush']
  }



];
